#+title: Notebook of a Return to My Native Land - part 4
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil

[[file:index.org][Back to chapter index.]]

Sunday, November 19, 2006

* Maior e Vacinado

- Hepatitis A
- Typhoid Fever
- Meningococcal Meningitis
- Diphtheria
- Tetanus
- Polio
- Cholera
- Hepatitis B (three injections)
- Yellow Fever
- Very large amounts of Lariam pills for malaria (interestingly
  enough, don't seem to have nasty side effects for me or Shahin,
  unlike many people we've spoken to).
- First-aid kit, with hydration, salts, etc - still to be purchased.

My arms hurt. Note to self: next time don't leave it all for the last
minute. In the context of vaccines, last minute is last two months,
really. Otherwise you may end up leaving the clinic with a much
lighter wallet, five injections on one arm, four on another, high like
a kite and sick as a dog. And wondering if it is really all right to
have that many injections in one go.

And remember to moan. I moaned so much that the very nice nurse Helga
gave me some of the kiddies sweets. Result.

* The Tide Has Turned

This Thursday two major milestones were achieved.

The first one happened in the morning, when I went to the Angolan
embassy to collect our passports. On them, one can find a beautifully
embossed sticker with the words "Angolan Visa". While holding it in my
hands, I could feel my eyes getting slightly moist.

At that point, I had the time and peace of mind to reflect a bit on
the whole visa process. To be fair to the Angolan government, they
were extremely efficient: the process was detailed on the embassy's
website (with the important exception of the 60 days "sell-by-date"
rule); once we complied with the complex requirements, they produced a
visa within three days; and they charged us 40 GBP each for it, which
is in line with a Gambian visa. The two unfortunate key points where a)
the lack of a tourist visa, which the government has already
addressed by legislative means, and which hopefully will start to
filter down to the embassies in the near future; and b) the
difficulties of communication with the local contacts. No solutions
for the latter as of yet.

The second major milestone was accommodation in Luanda. After finally
managing to speak to my auntie Linda and my cousin Rosa, they were
more than happy to have us for the time we need to stay in Luanda.

These two major achievements were only possible with the help of many,
many people, to which we are very grateful.

My usual optimism was a bit dampened, as I remembered Rui's
words. Elsa was bemoaning the difficulties their poor cousins were
facing in trying to get home. Rui, making a muxoxo, said: "You think
they're having a tough time now?! Just wait until they get to the
Banda!". Banda is how Angola is affectively known.

Still, I continue to claim the whole affair as a huge victory of
desenrascanço over planning.

Shahin protests most vehemently.

| [[file:part_3.org][Back to previous chapter]] | [[file:index.org][Back to chapter index.]] | [[file:part_5.org][Forward to next chapter]] |
