#+title: Nerd Food: On the UbuntuBox
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil

| [[file:index.org][Back to essay index]] | [[file:../index.org][Back to home page]] |

Thursday, June 19, 2008

* The Regular User

As with many other geeks, I find myself in the unofficial position of
"computer guy" for family and friends (F&F). This entails sorting out
broken computers, providing advice on new purchases for a variety of
devices and software packages, installing said devices and packages,
doing security updates and giving security advice, providing
mini-tutorials on applications, teaching basic programming - the list
goes on and on. The funny thing is, much like all other nerds, I may
moan about my duties but secretly I enjoy performing them. Sometimes I
get to setup people with cheap Ubuntu boxen, which they may complain
about a little in the beginning but eventually use in extremely
productive ways; and even on windows setups, I get to understand what
drives people to Microsoft and what its weak and strong points
are. Its a very instructive job.

Things got even more interesting since I bought my eee PC, a device
that is selling like fire in the polar winter. The eee PC helped me
understand a bit better how most people think. All along we, the Linux
community, have focused on providing a user experience that is very
similar to Windows: you may not have a Start Menu but you have the
Ubuntu logo; toolbars and menus are very similar and so on. Even the
newest eye-candy is similar to Mac and Vista's way of doing things
(although there's always the chicken-and-egg problem). The end result
is interesting: developers and regular Linux users are now convinced
that no one should have any difficulties at all moving from Windows to
KDE or Gnome; on the other hand, as soon as you sit a user down on a
Linux box, he or she immediately tells you that something is not
right. Objectively, the average user will probably not be able to
point out what's wrong, if anything at all, other than "this is not
Windows, can we not have Windows please".

The fantastic thing about the eee PC was that, of all people I showed
it to, not a single one said: bah, this is not Windows. Most of them
got on with the user interface immediately, and found it really
intuitive. In all my years of advocating Linux I never before seen a
reaction like this. I did absolutely no advocating whatsoever, no
mention about freedom or the superiority of free software. Just
letting them play with it was enough. As an example, my girlfriend has
been using Linux for over 5 years, and I get the periodic complains of
"why can't we just use windows" whenever I have some difficulties
installing a device, or I break the world on a dist-upgrade. But
within minutes of playing with the eee, her reaction was: "I want one
of these!!".

The reactions I've seen towards the eee PC are almost the opposite of
the few Vista users I've spoken to. Sure, Vista looks nice, but have
you tried installing a one-click wireless router? That's when F&F call
me out, when it all goes wrong with the "one-click" cheap product they
bought. But thing is, I can't say much in Ubuntu's defense either. For
example, I spent several days installing a Huawei e220 modem to
provide 3G Internet access to my nephews, and let me just tell you,
trivial would not have been a word one could apply to any part of the
process. Vodaphone's new clever GUI may be good for Vodaphone users
but I never got the damn thing to cooperate. True, the whole exercise
wasn't taxing for a nerd - hey, its fun to look at AT commands now and
then - but there is no way, just noooo waaaay a regular user would
have gone through the pain, even with the brilliant Ubuntu forums to
hand.

Now, before we go any further, I can already hear the complaints: "so
you've chatted to what, twenty people, and now you think you
understand the market?". Well, that much is true, I cannot claim any
statistical accuracy to my diagnostics. These are my opinions; the
entire article is based on empiricism and small samples. However, if
my line argumentation is done correctly and rightly interprets the
success of the eee, then there must be some truth to my views because
I've tried to align them with the eee. The market has given a verdict
on this gadget, loudly and unequivocally.

The eee PC is also a brilliant illustration of the huge divide between
regular users and the developers who are tasked with providing
software for them. At a moment in time where the Gnome community is
yet again rethinking the future of Gnome, not a single regular user
would find this debate interesting. This should send all the alarm
bells ringing, but unfortunately that doesn't seem to be the case. The
truth is, regular users don't want flashy 3D desktops, although they
can eventually cope with them; they don't need spinning cubes although
they may start using them once they understand it. What they really
want is simplicity. They have a simple set of tasks to perform, and
they want to do so cheaply and reliably, and they truly do not
understand why everything has to be so complicated and why do
computers have to change so much so often.

So what made the eee popular? In my opinion, there are two key points:

- Its cheap. No one would even have a look at it if it was 400 GBP
- Its easy.

These are the key selling points to a regular user. To illustrate the
second point, when I said to my girlfriend I was thinking about
installing Ubuntu Hardy on the eee, she replied in dismay: "Why would
you do that??".

* The Regular User Use Cases

The key thing to notice about the eee is that most users don't even
know its not running Windows. Its just an appliance, a bit like a
PlayStation, and thus there is no need to enquire about it's operative
system. Like an appliance, it is also expected to be switched on and
just work - the fast boot reinforces this idea. The interface provided
is also designed for the tasks common to the vast majority of regular
computer users, and allows them to find things fast. But, looking at
the wider problem, what do our regular users do with their computers?
I compiled a list of all use cases I found in my user base:

- Internet: email, browsing, playing on-line games and youtube;
- Listen to music, sync with their music player;
- Watch local video content;
- Talk with their friends: IM, VOIP
- Play (basic) games: on all cases, real gaming is done on the
  PlayStation;
- Work: word-processor by far, some spreadsheet use but "it's quite
  hard";
- Burning and ripping;
- Downloading: torrents, etc. Not very popular because "its
  complicated";
- Digital photo management: storage, some very basic manipulation
  (make it smaller for emailing);
- Printing: mainly for school/University; pictures in very few cases.
- In addition to these, some additional requirements crop up:
- Windows users all have proprietary firewalls and virus scanners;
- All machines are multi-user, and data must be kept private -
  especially with the youngsters;
- Machines must withstand battering: switched off at any point, banged
  about, dropped, etc;
- Internet connectivity is vital, ADSL, cable and 3G are
  used. Computers are useless without the Internet;
- Wireless around the house is vital. External wireless is nice, but
  not frequently used because "it's too complicated";
- Costs must be kept exceedingly low as IT budget is normally very
  low;
- That's it. You'd be amazed with the percentage of the market one
  covers with only these use cases; not just doing them, but doing
  them well, like a PlayStation plays games.

And what are the biggest complaints about computers?

- They're really hard. Installing hardware and software is a
  nightmare, and they'd be stuffed without the local nerd;
- They break easily. One of my Vista users is still in disbelief that
  installing wireless drivers could cause the DVD drive to stop
  working;
- They're expensive. Sure you can get a cheap'ish box but then
  everything else is expensive (software, peripherals, etc);
- They change far too frequently. Most users just about got around XPs
  user interface just to see it all change again;
- They're insecure. They don't know how or why but that's what they've
  heard. That and the constant popups that look like viruses.
- On one hand, the regular user is quite advanced, making multi-user
  and networking a central part of its computer experience. On the
  other hand, he/she is very naive: the vast majority of computing
  power goes under-utilised - the OS gobbling most of the resources
  for no good reason - and the majority of software expenses easily
  avoidable by using freely available applications. Regular users
  haven't got nowhere near using Media Centres, "clever" media
  management software, or even connecting their PCs to the TVs. All
  these things they consider "advanced" and yet nerds and more savvy
  users have been doing it for years. One cannot help but feel that
  there is a massive market out there for the taking - a market that
  Vista cannot aim to grab because it's diametrically opposed to its
  needs - and yet, no one else seems to find the path to its door.

* UbuntuBox: The Hardware Platform

The rest of this article is an Ubuntero Gedankenexperiment: if I was a
manufacturer, what sort of box would I like my F&F to have? What would
make my life and their life easier? The short answer to that question
is a PlayStation 2 like box but with PC-like functionality. The long
answer is, well, long.

I'm not going to bother with engineering reality here - I'm sure some
requirements will be so conflicting they cannot possibly be
implemented. However, I've got zero experience in hardware
manufacturing, weights, cooling, large scale deployment and so on - so
much so that I'm not even going to bother pretending; any assumptions
I'd make would be wrong anyway. So, to make matters easy, I'll just
ask for it all - impossible or not - and wait for the reality check to
come in.

The first, very different thing about our box is that it's not a
computer. Well, inside it is a regular PC of course, but it doesn't
look like one. It is designed to look exactly like a DVD player, and
to fit your living room. A bog-standard black-box with a basic LED
display would do. Inside, it has:

- Multiple cores: four would be ideal, but at least two. They don't
  have to be particularly fast (1.x Ghz would do, but I guess 2 Ghz
  would be easier to find);
- 4 GB of RAM: can be the slowest around, but we need at least 4; the
  more the merrier, of course;
- 250 to 500 GB hard drive: the more the merrier. Doesn't have to be
  fast, we just need the space;
- Average video card: key things are RGB/HDMI and TV out; resolution
  decent enough to play most games (not the latest);
- Loads of USB ports;
- RW DVD drive;
- Analog TV + DVB card (for FreeView in England);
- Wired and Wireless Ethernet;
- Sound card with 5.1 surround sound: doesn't have to be a super card,
  just an entry level one would do;
- SD card, compact flash readers;
- Ability to control the box with a remote control;

And now the key limiting factor:

- The overall cost of the box must not exceed 200 GBP. This may
  require some tweaking, e.g. if raising it to 299 means we can put
  all features in, it may be worthwhile.
- Notice that all the hardware will be standard on all boxes of the
  same generation. This is all commodity hardware - certainly nothing
  proprietary - but without the heterogeneity that is associated with
  it. Note that control is a key feature - the limiting of user and
  vendor freedom to swap things at will. We'll return to the topic
  later on, as I'm sure it will prove controversial.

Now, how does the box behave for the regular use case? Well, you buy
it, plug it in, set all the cables up and start it up. You will see
only two things on boot: the logo (say the Ubuntu logo) fading in and
out, and the console password. That's it. No BIOS, no flashing
X-Server, nothing else. Within a few seconds you'll be prompted for
the console password and given an option of not needing a password in
the future (Note: console is _not_ root). Lets leave the desktop at
that for the moment as we'll cover it properly in the next section.

What about Internet access, you ask? Well, you will need to buy one of
the available modems:

- 3G;
- ADSL;
- Cable.

Each of these modems are made available at market prices (i.e. as
cheap as possible); however, they will have been officially and
exhaustively tested and stamped with a "UbuntuBox compliant vX" or
some such, where vX is the box's generation. To be compliant means
that your hardware has been throughly tested and is known to work with
the hardware and software in a given generation. When you plug any of
these devices after console login, a simple wizard will appear asking
you to choose a provider. Each provider will have been also part of a
certification program before inclusion.

The other networking device is an Ethernet Switch. This is only
required if your modem does not come with switching abilities (maybe
in the 3G case). Network Manager already does a pretty good job of
this, so all you'll need to do is setup the network on your console
session (SSID, etc). You can use a USB keyboard for this or just
endure typing from the remote control.

Note that the certification requirement is extended to all hardware
used with the box. In other words, there is a pretty draconian control
on the hardware platform. Users are, of course, free to do as they
wish with the device they bought, but if they go down the uncertified
route, all support contracts are rendered void (more on this
later). The truth is, its impossible to provide cost-effective support
to all possible permutations of off-the-shelf hardware - a fact all
Linux and Windows nerds are all too aware, as are Mac engineers. There
will always be some weird combination that makes things break, and it
can take many, many man-days to fix it; when you have 1M boxen out
there, this cost would be prohibitive. The only way is to control the
standard platform.

For all of its closeness, the certification process is actually open
when compared with other companies. All the criteria involved is made
available in public websites, APIs with all the hooks required to
extend wizards are public (with examples), companies are free to do
public dry runs and any company can request a slot for
validation. Perhaps some cost needs to be associated with the process
(time is money after all, and we must discourage the less serious
companies), but in general, the process is fair and public. The tests,
however, are stringent; hardware that passes _cannot_ fail when
deployed in the wild.

One final note with regards to entry level hardware. Some people may
not be aware, but the computing power available as standard today is
incredibly high. For example, one of the PCs I maintain has a 1Ghz
CPU, 512 MB of ram, 10 GB hard drive and an average ATI card; I bought
it for 60 GBP. This machine runs Ubuntu Hardy and sometimes has to
cope with as many as 3 users logged on. It doesn't do any of the 3D
Compiz special effects due to the dodgy ATI card, but it does pretty
much everything else. You'd be surprised on what you can do with the
slowest RAM, cheapest sound-card and so on.

* UbuntuBox: The Software Platform

By now you must have guessed that the box would be running Ubuntu; but
this is not your average Ubuntu. Using an interface along the lines of
Remix, we would make a clear statement that this is an appliance - not
a PC. As the eee has demonstrated, perceptions matter the
most. Remix's interface will remind no one of Windows, whilst at the
same time making the most common tasks really easy to locate.

In addition to regular Ubuntu, the software platform would provide,
out-of-the box, complete media support. This entails having GStreamer
will all the proprietary plugins, Adobe's flash and any other plug-ins
that may be required for it to play all the media one can throw at it.

The UbuntuBox is mainly a clever Media Centre, and, as such,
applications such as Elisa, Rhythmbox/Banshee, F-Spot, etc are at the
core of the user experience. These applications would need to be
modified slightly to allow for a better multi-user experience
(e.g. shared photo/music collections, good PVR and DVB support, etc),
but on the whole the functionality they already provide is more than
sufficient for most users.

As with the hardware side, the software platform is tightly
controlled. Only official Ubuntu repositories are allowed, and all
software is tested and known to work with the current generation of
boxen. And, as with hardware, the software platform is made available
for third-party who want to deploy their wares. An apt interface
similar to click 'n run is made available so that commercial companies
can sell their wares on the platform and charge for it. They would
have to go through compliance first, of course, but if the number of
boxes out there is large enough, there will be companies interested in
doing so. This would mean, for example, that a games market could
begin to emerge based on Wine; instead of having each user test each
Windows application for their particular setup, with many users having
mixed results, this would put the onus of the testing on the company
owning the platform and on the software vendor. Games would have to be
repackaged as debs and be made installable just like any other Debian
package. Of course, the same logic could be applied to any windows
Application.

As I mentioned previously, boxen come with support contracts. A
standard support contract should provide:

- Access to all security fixes;
- Troubleshooting of problems, including someone remotely accessing your machine to help you sort it out.
- Due its homogeneity, UbuntuBox is very vulnerable to attacks. If an exploit is out in the wild, large number of boxen can be compromised very quickly. To make things a bit safer, the platform has the following features:
- SELinux is used throughout;
- All remote access is done via SSH and is only enabled on demand (e.g. when tech support needs access);
- All users have passwords and must change them regularly;
- There is an encrypted folder (or vault) for important documents, available from each user's desktop.

Finally, notice that binary drivers and proprietary applications are
avoided when possible - e.g. Intel drivers would be preferable to
nVidia, provided they have the same feature-set. However, where the
proprietary solutions are technically superior, they should be
used. Skype springs to mind.

* UbuntuTerm

Readers may be left wondering, "this is all very nice and dandy, but
am I supposed to do my word processing using a TV?". Well, not
quite. Whilst the TV is central, its use is focused on the gaming and
Media Centre aspects of the box. If you want to use UbuntuBox as a
regular PC, you will need to buy a UbuntuTerm. Just what is a
UbuntuTerm? It is a dumb terminal of "old" in disguise (e.g. LTSP). It
is nothing but a LCD display of a moderately decent size (19" say),
with an attached PC - the back of the monitor or the base would do, as
the hardware is minimal. The PC has a basic single core chip with low
power consumption to avoid fans and on-board video, sound and wireless
Ethernet. It is designed to boot off the network if BOOTP can be used
over wireless; if not, from flash. Whichever way it boots, its
configured to find the mothership and start an XDMCP session on
it. Its price should hover around the 100 GBP mark.

As with any decent terminal these days, UbuntuTerm is designed to fool
you in believing you are sitting on the server. X already does most of
the magic required, but we need to take it one level further: if you
start playing music, the audio will come out of your local speakers
via pulseaudio; if you plug your iPod via its USB port, the device
will show up on your desktop; if you start playing a game, the FPSs
you get remotely will comparable to playing it on the server. As with
everything else mentioned in this article, all of these technologies
are readily available on the wider community; its a matter of
packaging them in a format that regular users can digest (see Dave's
blog for example).

The standard hardware on a UbuntuTerm is as follows:

- Low RAM, basic video card;
- Speakers attached to monitor;
- SD Card, compact flash readers;
- WebCam, headset;
- Lots of USB ports

A house can have as many UbuntuTerms as required, and the server
should easily cope with at least 6 of them without too much trouble,
depending on what sort of activities the users get up to.

Finally, in addition to the UbuntuTerm in hardware, there is also a
UbuntuSoftTerm. This is nothing but a basic Cygwin install with X.org,
allowing owners of PCs to connect to their UbuntuBox without having to
buy an entire UbuntuTerm.

* Conclusions

UbuntuBox is an attempt to ride the wave of netbooks; it also tries to
make strengths out of Linux's weaknesses. The box is not may not live
up to everyone's ideals of Free Software, but its main objective is to
increase Ubuntu's installed base, allowing us to start applying
leverage against the hardware and software manufacturers. The design
of the box takes into account the needs of a very large segment of the
market which have basic computing needs, but don't want to became
experts - just like a PlayStation owner does not want to know the
ins-and-outs of the PowerPC chips.

The UbuntuBox is an appliance, and as such is designed to be used in a
fairly rigid number of ways, but that cannot be avoided if one wants
to stay true to its nature. The more freedom one gives to users, the
worse the end product will be for the Regular User, which cares not
for intricate technical detail.

Note also I haven't spent much time talking about business models for
the company providing UbuntuBoxen. The opportunities should be there
to create a sustainable business, based on revenue streams such as
monthly payments for support, fees from OEMs, payments to access the
platform (content providers). However, I don't know too much about
making money so I leave that as an exercise to the reader. The other
interesting aspect is comunity leverage. If managed properly, a
project of this nature could enjoy large amounts of comunity
participation: in testing, packaging, marketing, support - in fact,
pretty much all areas can be shared with the comunity, reducing costs
greatly.

All and all, if there was an UbuntuBox out there for sale, I'd buy
it. I think such a device would have a good chance of capturing this
illusive segment of the market, giving Linux a foothold, however
small, on the desktop.

| [[file:index.org][Back to essay index]] | [[file:../index.org][Back to home page]] |
