#+title: Notebook of a Return to My Native Land - part 9
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil
#+HTML_HEAD: <link rel="stylesheet" href="../css/tufte.css" type="text/css" />

[[file:index.org][Back to chapter index.]]

Sunday, January 07, 2007

* Ilha

Luanda's Marginal is the heart and soul of the city. It is a large
road that circumscribes the bay, offering an excellent view. The bay
is strikingly beautiful, both night and day, but more so at night,
when the bright city lights are shinning and the darkness hides the
less pretty parts. Its definitely worth seeing it during the day,
though. As you walk up the Marginal there are quite a few colonial
buildings that have been renovated, like the National Bank, and some
new ones being built such as the high-rise Sonangol building -
Sonangol being the state's oil company. Unfortunately, like in all of
Luanda, a stunning large building is followed by either a bit of
wasteland, some run-down flats in various stages of decay or, at best,
a fenced-up area reserved for a construction site. And the sidewalks
on the city-side of the Marginal are of the usual atrocious
standard. The bay-side does appear to have been properly maintained,
or recently redone, and it even sports some benches for better gazing
at the sea.

The port of Luanda sits at one end of the Marginal. Its impossible to
underestimate the importance of the port since it is the source of
almost all goods you find in shops. The country's industrial output
outside of oil is down to practically zero and agriculture fares a
little bit better, but not much, so imports rule the day. In addition,
since the roads linking the provinces were badly affected by the war
and years of neglect, trucks cannot come from across the border or
other provinces to bring in the goods to Luanda - the city where most
Angolans live. So they are transported either via plane or, more
likely, via large ships. The situation is changing with the
reconstruction effort, which has already resulted in the reopening of
many key links, but you still hear a lot of people in Luanda complain
that fruit and meat rot down south in Lubango because they haven't got
anyone to sell it to, while at the same time folks in the capital are
paying top prices for foreign meat and juices, some of very dubious
quality.

At the other end of Marginal is the entry into the Ilha, or island of
Luanda. Ilha is a long strip of land that sits in front of the bay, as
if designed to shelter it, to protect it. At one time Ilha was a real
island - hence the name - and what is now the road into it was a
narrow stretch of water. The Portuguese decided to link it to the main
land, and filled the gap with rocks. This was done back in the days
where haste and bravado ruled the day rather than engineering, so, as
you can imagine, not a lot of analysis was done to understand the
impact of the change. Turns out the little stretch of water had
actually an important role to play, as it allowed water to flow into
the bay. Once it was gone, little islets started appearing in the bay
in low tide. Unfortunately, to make matters worse, the government has
recently approved a polemic project that will modify the bay
dramatically, reclaiming some land from the sea to enlarge the
road. It may also add some large buildings to the other side of the
Marginal, which would be a real shame. One just has to hope that this
time the environmental impact analysis was slightly more thorough.

There's a long road that traverses Ilha. Travelling up it, one can see
musseques alternating with large beach cafes, nice private houses and
the usual bits of wasteland but this time with the ocean at the
end. Ilha is the closest beach to town, so its pretty busy during the
day, in particular on weekends and holidays. On our first few visits
to Ilha we were not aware that the cafe's "private" beaches were not
actually private. So we went to random bits of beach, and
unfortunately most of them have a lot of rubbish. People here are
still very casual with their rubbish in Angola, and they throw it all
over the place. Granted, the government has sorted out the huge crisis
of waste collection that existed a few years ago, but now the problem
is one of social conscience. I recall those days in Portugal when
people used to go to the beach and leave the sand full of Coke cans
and plastic bags and thought nothing of it. Somehow it became socially
unacceptable to do that. The problem still exists there, of course,
but its nowhere nearly as bad as it was in the eighties. Angola is a
lot like Portugal back then. People still finish their cans or bottles
and casually throw them into the sea, and this includes the Portuguese
and diaspora here too, who seem to copycat the locals. As a result,
when you go to one of the non-concessioned beaches in Ilha, you'll
have to put up with crisp packets and cans laying around. Not huge
amounts, mind you - its not a dump or anything - but there's enough of
it to give it a "polluted feel". You can't just choose any random bit
of sand, you need to look for a clean area.

Of course, as we found out, only the commoners go to these
beaches. The cafes have concessioned beaches which are actually
available to the general public; you can go there without spending a
dime. In most cases you can even access these beaches by walking up
from the sand and there are no security guards to stop you. However,
there is some kind of invisible force here at work, some kind of
unexplained social magnetism law that creates a very effective
barrier, disallowing the poorer people of the musseque across the road
from stopping there. They do trek past these places, some times in
small groups, other times one lone individual or two, but somehow
never seem to stop for long. The crowd at the cafes and their beaches
is very much an in-crowd. Five metres down the road everyone is black,
the two of us standing out; here, there's an eclectic mix of black,
white, chinese and mulatto; Portugal's Portuguese is spoken as
frequently as Angolan Portuguese and in some corners one can hear
English, French and Mandarin. The beaches are much cleaner, if not
totally spotless. However, we found that the best way to enjoy these
beaches is at an ever so slight distance, as the air is somewhat
rarefied and the poshness and pseudo poshness is, at times, too hard
to bear. So we tend to stay there only when we're meeting someone; the
alternative is to sit twenty or thirty meters from one of these cafes,
where one gets the best of both worlds. Maybe we struggle because we
are the only ones to arrive at these places in a candongueiro or a
mashed-up taxi, and that immediately puts us on the lower strata of
society. It appears that we've also hit the invisible barrier and been
forced back, only perhaps just not as far back as most
locals. However, if you ever come to Luanda you must try at least once
some of these haunts: Sao Jorge, Miami, Chill Out, Tamariz, Jango
Veleiro. There are many to choose from. Some of these places are
really, really nice inside. For instance, Miami Club could be in any
beach in Ibiza, so cool and hip it is. The others are at the same
level, if not higher.

Although there are quite a few places to go out in Luanda, Ilha seems
to be epicentre of night-life. The beach clubs get even busier at
night. Restaurants are busy too, and some of them are quite
remarkable. For instance, Cais de Quatro has an excellent view of the
bay and excellent food. When you're finished with the food, you can
walk over to its sister-space Bar In, always ready to greet you. These
places are quite enjoyable at night, even those which seem too
pretentious during the day. I suppose its a mental thing. Perhaps we
feel posher at night. But be prepared to spend, as a dinner at Cais de
Quatro for two people wont be any less than 100 USD (8000 Kwanzas).

Ilha is our default location here in Luanda and we've been to it many
times. Whenever there's nothing else planned, whenever our contacts
are not around and the sun is shinning, we do the fifteen minute walk
to Mutamba, turn right towards Nando's and descend towards the
National Bank. There, people congregate as if in an invisible bus
terminal. Most Europeans only see a parking lot and some wasteland but
Angolans can clearly see a large central candongueiro and taxi
interchange. There are many like these scattered around town. Just
wait a few minutes and you'll hear someone shouting "Ilha, Ilha" in a
loud, almost mechanical voice. On hearing this voice, particularly on
busy days, the crowd springs in to life. Everyone reacts
simultaneously to the call and attempts to board the vehicle,
instantly disregarding any queueing that may have existed till
then. If you're fast and lucky enough to get in, you'll be in Ilha in
fifteen minutes. If not, no matter. Wait a few minutes more and the
next taxi or candongueiro will arrive. Although they don't run to any
known timetable, except perhaps an invisible one, they come as
frequently as buses in Central London.

One day, as we were returning from Ilha, the harsh reality of life in
Angola hit us straight in the face. Suddenly there was some commotion
in the candongueiro, but we couldn't immediately understand what was
the reason for it. To our right there was a private ambulance, and,
like us, it was crawling at a snail pace towards town. We were all
stuck in the horrendous Luandan traffic, somewhat less usual in Ilha
at that time of day. People inside the van were shouting at the
ambulance, and eventually I understood what they were saying. "You're
an ambulance, why don't you go and pick up the kid?! If there's no
money you don't do any work, you don't care if people die!". I
couldn't hear the replies of the ambulance drivers, if any were
said. Then, on our left we saw the inert body of a little kid, perhaps
some twelve or thirteen years old. There was blood on his face and on
his shirt. Cops where surrounding the body, but it clearly had been
moved from the middle of the road to the side, to the gutter, so that
the traffic could flow and it was obvious the move was done without
any regards for internal injuries. There were no stopped cars or bikes
near the cops, so one was forced to conclude that this was a
hit-and-run. If the kid wasn't already dead, he was sure to die due to
lack of medical care. We didn't halt the candongueiro to figure out
what was going on, to try to convince the private ambulance to
stop. Instead, like everybody else, we just kept on going, complaining
about the state of affairs but doing nothing about it. This is
probably the hardest thing about living in a poor country: the need to
develop a thick layer to insulate you from reality. I wrote a poem a
while ago, called "Little Black Child", and it came to my head then:

#+begin_verse
oh, my little black child
with your young, naive face
oh, how much i wish i could help you
hold you in a tight, warm embrace
you are our hopes, our dreams!
you are the future of our race!
but you dwell in a far, far away slum,
where you live, and where you die without a trace.
you are a nameless, shirtless body,
living everywhere but belonging to no place.

oh, my child, this is not your world
you have no nation and no state
you must be deprived amidst all the riches;
and, amongst all knowledge, you must learn only hate.
you see, my child, they have broken us, broken us bad
they have left us in a very sorry state.
they took our civilization, our glories, our past.
they erased us from history and determined our fate.
we are nothing and no one now, child;
there is nothing we can create.

child, my heart is shattered
but i cannot help you, i cannot
you are destined not to learn
not to know the proud history of our lot:
of the great yoruba, the brave kwanyama;
of the mighty warriors who stood tall and fought.
of those who ran away from the chains;
of those who tried but were caught.
they all gave their lives for yours, child
and they all have died for naught
for you have no future;
and, when you die, no one will spare a thought.
#+end_verse

Suddenly it struck me that our deepest feelings of sorrow come when
one can't actually do anything to change the world; but, when time
comes for action, many of us are found wanting. Morrissey stated it
best: "it takes guts to be gentle and kind".

** Fortaleza

On Christmas day we decided to visit Fortaleza. Fortaleza, or "Big
Fort", sits at the entrance of the Ilha junction, towering above it
and overlooking both the bay and the city behind it. Fortaleza is a
very old Portuguese castle-like building, originally created to defend
the city from other predatory colonial nations, and these days it
hosts the army's museum. Standing from Marginal, Fortaleza gives you a
deserted, not-open-to-the-public look, but we were not fooled by it
and climbed the many steps to the top. As we got close to the summit,
we bumped into closed gates and a couple of army officers behind
them. These gates are like a parable designed to explain Africa to
Europeans. Here we are in a public building, open to all
Angolans. Yet, the closed gates - they appeared to have been closed
for a while - deny access to it during its opening hours. The soldiers
behind the gates sit there, day in, day out but - and here's the crux
of the parable - instead of opening the gates, they direct people to a
beaten track around the bushes to get access to the next flight of
stairs. This, to me, represented the whole philosophy of survival in
Angola and perhaps even of Africa at large. Lord knows how many hoops
one has to jump through to get the authorisation to open up a set of
gates, and no one would dare doing it without clearance. But you do
have the authority to create a new path in the bush, no one is going
to hold it against you. Whenever the system raises up a barrier,
people always found ways of routing around it, in this case all too
literally.

Once you get to the top, you are rewarded with a panoramic view of
Luanda, stretching as far as the eye can see. Since Fortaleza is a
circular building, you can walk around it to view the different parts
of the city. Behind it, there is the rather large Praia do Bispo
musseque. Many kids seem to come up from the musseque to gaze at their
city. However, perhaps due to the large presence of the military, the
place appears to be quite safe. There were some Portuguese and French
families up there, and the kids where roaming freely. Nevertheless,
make sure to exit via Marginal - never by Praia do Bispo.

Watching the sunset from Fortaleza is an enriching experience.

** Cabo Ledo

One sunny Sunday we headed off to Cabo Ledo. Normally you need to
leave early in the morning as the trip takes a couple of hours or so,
but this is Angola and everyone works in Angolan Time, so after a long
wait we ended up leaving at one'ish. We crossed town and headed
towards Benfica. Here you can see some nice views of Mussulo, Curimba,
and the other islets that compose this little archipelago. On the way
we stopped at the Miradouro da Lua, the Moonscape. This is a really
high, really eerie sort of place, and it does indeed remind you of the
Moon or some other inhabited planet.

A good few miles down the road, Barra do Kwanza appeared. This is an
immense, unimaginable long stretch of beach, but unfortunately we only
managed to see it from afar. We then headed towards the famous Kwanza
river, the one which the currency is named after. Unlike Namibia,
Angola is very fortunate in terms of drinking water. There are many
large rivers, and most of them flow even during the dry season. The
Kwanza can be forded via the new toll bridge, costing around 200
Kwanzas per vehicle. The toll has to be paid both ways, so it will set
you back 400 Kwanzas in total. The river is a rather large green
stream, flowing at pace. From the bridge it looks rather clean, unlike
most European rivers. I suppose Angola still hasn't got the bane of
industry to destroy her rivers.

Eventually, after a long drive, we reached an unsuspecting sign on the
road. A rather small crab with no writing on it, or none that I can
recall, marks the road leading down to the beach in Cabo Ledo. Its so
small we went past it and had to come back. From then on, the
remainder of the way is a "picada", or bush road, full of holes and
can only be done in a big jeep. Its only a few metres long but it
takes a while to get there because the road is so bad. This is in
striking contrast with the road leading up to the detour, which for
the most part has been recently redone. All and all, it is a pleasant
drive, minus the last leg of the journey.

In Cabo Ledo, we were invited to Paulo's house. While at high-school,
Paulo was taught by both of my cousins and is now a fairly successful
entrepreneur. Amongst many other dabblings, he is now building a set
of bungalows near his house in Cabo Ledo. He is a nice, affable chap,
but his most distinguishing trait is an innate ability to stir
controversy in any conversation. In someways, all mulattos have this
ability, its just something we're really good at. I suppose, not being
part of any culture in particular, but being able to claim all of them
as your own, makes you a sort of a rebel from inception. And we all
like to brag, to stir trouble. Mulattos always remind me of the Monkey
in African fables: the king of mischief, forever causing
trouble. However, even for a mulatto, Paulo has this trait in a
concentrated, distilled, potent form. You spend every minute with him
in permanent laughter, holding on to your insides. For instance, when
asked whether he was going to have any partners in the bungalows
business, he said something along the lines of: "Partners?! Are you
crazy? Trust no one! If I hire a white man, give him a couple of
months and he'll be running the business, and will find some ways of
kicking me out! If I get a mulatto he'll think he's cleverer than
everybody else and find all sorts of ways of robbing me blind! And if
I get a black man, you can imagine the amounts of parties he'll
organise here when I'm not around, besides robbing me!!! You can't
trust these people!!". He says this in the serious, loud, high-pitched
voice all Angolans use when absorbed in good conversation, a tone so
high that sounds to most foreigners as if we're having an argument
when in reality its just the usual friendly banter. Paulo helped me
understand the dual nature of the mulatto. When asked whether he was
Portuguese, he answered yes. But, was he Angolan? Yes, of course. And,
what was he, white, black or mulatto? All of the above, but of
course. Yet, all the same, he would have no problem slagging "those"
white, blacks and mulattos, and when he was slagging them he was not,
of course, part of them. But he was, too. That's what we are, really,
a sort of a chameleon. During the world cup I had no problems
supporting Angola, even against Portugal, but also supported Portugal
with equal fervour in all games - except when playing against Angola -
and, of course, one has to always support Brazil. After all, one must
not forget that most of the black Brazilians are really Angolans. The
logic has always been so crisp that I never really reasoned about it
that much. Its only when I had to explain it to my English and
Portuguese friends that it struck me how complex our feelings of
belonging are. Everybody else has a country; we have none, yet we have
many.

Paulo had many guests in the house, an eclectic mix of Angolans and
Portuguese. After saying hello to all of them, we went down to the
beach. It was mostly deserted, with the fishing villages at the
bottom. Occasionally some fishermen walked down towards their
huts. The beach in Cabo Ledo is large, full of lovely whitish sand and
very clean. It was slightly windy on the day, but the sun shone so it
was still quite hot. We had a nice swim and spotted some fish while
snorkeling, but not huge amounts as the current was strong and we were
afraid of going too far. After the swim we went back to the house and
had some amazing grilled lobster, freshly caught by the
fishermen. They sell a kilo of lobster for 700 Kwanzas, which sounded
great until we found out from Paulo that they were selling it for 400
Kwanzas just one year ago. Prices have gone up dramatically, as there
are many more people coming here from the city. We spent the rest of
the afternoon chatting, eating lobster and drinking. Around nine
o'clock we started to drive back. Not many people drive in Angola at
night, and its easy to understand why: the roads are pitch black
dark. I've only experienced this level of darkness once, in Green
Cape. Its impossible to describe it, its so dark your window looks
like its covered with a thick black sheet of paper. If you look up you
can see the starry sky, everything else is covered in darkness. As we
drove towards the city we kept on wondering what would happen if the
jeep broke down somewhere in the middle of this emptiness. And, in
fact, we went past a couple of trucks that seemed to have had that
fate, with the drivers sleeping underneath them, waiting for rescue in
the morrow. The drive back to Luanda was uneventful and we managed to
get back home without any problems.

** Mussulo

We spent New Year's eve in Mussulo. As I mentioned earlier, this is
the largest island of a small archipelago off of Luanda. While Ilha is
mostly reserved for day outings, Mussulo is the touristic destination
of choice to spend a couple of days or longer stretches of
time. However, the snag is you really need to have a house there - or
have a friend who has a friend who has a house there - because there
aren't many places where you can stay, and those that do exist are
rather expensive. A bungalow can be as much as 100 dollars per person
(8000 Kwanzas) per day. You can bring your tent and camp in the wild
but this is not recommended, not just for fear of thieves but also
because you won't be able to shower or wash unless some kind soul
allows access to their house. We were lucky to have Elsa, who knows a
really friendly couple whose parents have a house in Mussulo. After
catching a lift with another mate, we got ferried across by a
candongueiro (the boats are also called candongueiros). These motor
boats are actually pretty good, not too overloaded and even have
life-jackets. However, being New Year's Eve the prices had been
greatly inflated: we paid 1000 Kwanzas instead of the usual 500, the
additional 500 being the "boas-festas" for the boat drivers. In
Angola, even more so than in the financial markets, all traders react
in nanoseconds to the smallest fluctuation on the demand-supply curve
and adjust their prices accordingly.

The trip into Mussulo was very nice, with a fairly calm sea. To our
left we could see the Curimba island, deserted these days, but at one
time inhabited by priests. The remains of a church are still
visible. Further to the left there's another desert island, but this
is mainly a wild life sanctuary and there is nothing on it other than
lots of mangroves and birds. After a fifteen minute boat ride, we
reached our destination. Elsa and the rest of the guys were coming on
another boat, and met us at the island a few hours later. In the mean
time, we spent our morning enjoying the nice, quiet beach. Mussulo is
actually quite large, and its full of houses constructed in a
haphazard manner. There aren't any roads, or any organisation. People
just bought land and made their houses. Some of these houses are
really close to the sea, so much so that if you walk up the beach
you'll frequently need to cross someone's property to be able to
continue going forward. They don't appear to be that safe,
particularly when the sea is rougher. Those who can afford it spend a
lot of money on their beach houses and, as a result, they look
stunning.

Once everyone got there and settled in, myself and the girls went to
the contra-costa, while the other boys went fishing. Contra-costa is
the other side of Mussulo, facing the high seas. Its actually a bit of
a walk to get there, around half-hour or so, and navigating through
the sand can be a bit tiring. We walked past a little village where
the real locals live, and we're fortunate enough to enlist a little
girl as a guide. Somehow we had managed to get a bit lost and we're
going the really long way. She took us all the way to our
destination. Mussulo's contra-costa has a lovely beach, and unlike the
other side its mostly deserted, with only little bamboo huts here and
there. Most people don't really like coming this far. The sea is a bit
rough here, though. The currents are really strong, and you can tell
you're on high-seas as soon as you get in. However, if you're brave
enough to get in you'll be instantly rewarded: the sea is full of
fish. Huge schools roam undisturbed, literally two or three metres
from the sand. Snorkeling here is absolutely fantastic, but one cannot
avoid feeling a bit afraid, since when there's pray there are always
some predators lurking around. Shahin was a bit afraid of going too
far, but myself, Elsa and Dora spent almost all the time in the water
spotting different kinds of fish. We returned before dusk for dinner,
as its not wise to walk around in the dark.

New Year's eve was all about eating food, drinking, swimming, catching
some sun rays and eating some more. At night, we had a meal at the
house and then set up a table five metres from the sea. There we had
the traditional raisins and sweets and some champagne. It was a quiet,
subdued, family affair, but it was very nice - probably one of the
most memorable New Year's I've had. I suspect this was also quite
memorable for Shahin, as it was the first time ever she slept in a
tent. Setting it up was the usual nightmare, but we had the help of
all the boys and girls so we managed to get it up fairly
quickly. After some initial fears, and after putting lots of sand
inside the tent, Shahin managed to cope with it all reasonably
well. The local animals and insects also decided to cooperate by not
entering the tent, which really helped. I can only imagine Shahin
finding a spider at 5 o'clock in the morning and waking up the whole
of Mussulo with her screams. Next day myself and Shahin walked up
almost all the way to the Lingua, one of the ends of the island,
taking us around two hours in total. We walked past the expensive
tourist bungalows, and they do look rather nice. There are also many
large houses. We returned to Luanda after lunch.

A few days later we came back to Mussulo. This time we came on the
boat belonging to the owner of the house. The boat departed from the
Elf dock, much less protected by the islands and so suffering from a
much rougher sea. Also, the boat was much smaller. To make matters
worse, we were supposed to get there for 12 o'clock but only arrived
at around three, a time at which the sea is very rough in this
particular spot. We started our trip but the boat kept on dipping into
the waves in a way that didn't look too safe. The girls behind me
didn't look too good. Eventually, after a few minutes of fighting
against the waves, our intrepid captain Luky determined that we could
not proceed with this much weight and we had to go back. We then drove
to another private dock further down the road, much more sheltered
from the high seas, and departed from there. This time the trip was
quiet and we got there without any major problems. Once we got there,
I went fishing with the boys. It was an extraordinary experience. I
actually thought I hated fishing, but this was because I associated it
to catching fish. It couldn't be further from the truth. It would be
more accurate to call it boating, or something similar. Fishing is
only incidental; one spends most of the time gazing, looking at
wild-life - some of the boys spotted large turtles - and drinking
beer. We stopped near Curimba and caught some mussels for fishing. As
we were on our way back we caught a Barracuda, which was just as well
as we needed some fish for dinner. Next day we also went fishing, but
this time on a larger boat. We didn't catch anything but went really
far. That's when I realised how big Mussulo is. It continues on
forever, becoming more and more sparsely populated, with less and less
beach houses. We didn't even get to the end of it. After fishing, we
had lunch and played some volleyball, but unfortunately my team got
humiliated by the old codgers yet again. Not long after that we set
sail back to Luanda.

** Other Adventures

Other than the outings we had, I suppose the most interesting
adventure was the paludismo episode. Paludismo is the Portuguese name
for Malaria. I had a couple of days of fever, around 38 degrees, but
it all went away. The first fever was funny in itself: we bought a
mercury thermometer in England, one of those cheap jobs. The thing is,
not only does it take some practise to read it properly but you also
have to wait four minutes to do each reading. And to think we actually
debated buying a ten pound digital thermometer but decided against it
in the end. That's when Jojo's words came to mind, that one time on
the subject of condoms, but totally applicable to the situation at
hand: "hey man, that's not exactly the sort of stuff you want to save
money on...". Oh well, onwards. After a good couple of days with no
temperature, I had another day of fever. We had decided to go to the
doctor's if I was still feeling ill in the morning but, lo and behold,
I was fine again next day. A few days went by and I got feverish
again. We went up to the local private clinic, five minutes walk from
my aunty's house, and did a basic paludismo test called the Gota. It
came up negative. We then went to see the doctor, a Cuban GP. She
spoke a really broad Spanish, and I was just about able to keep up
with her. Shahin remains convinced she wasn't speaking in Spanish, so
broad the Cuban accent was. The doctor, somewhat jokingly but with a
hint of seriousness, told me that I must be Angolan. You can always
tell a foreigner from an Angolan because all Angolans do the cheap
Gota test for paludismo instead of the more expensive analysis. The
problem is the Gota is not entirely accurate, more so when you are
taking the profilaxia - this is the name given to the Lariam treatment
recommended in England. After shouting at us quite a lot for doing the
profilaxia - she is adamant that the damage done to the liver is much
greater than any benefits - she gave me a paper with a whole load of
tests to take. We had already spent sixty dollars just to see the
doctor and this new battery of tests set us back another sixty
dollars. But, since we could not account for the fever we had no
option but to take these tests. One of them was a blood test, but
Shahin kept a watchful eye on the nurse to make sure she was using a
new needle and clean gloves. About a couple of hours later the results
where ready and we went back to the doctor. She had a look at the
results and, indeed, I had paludismo - the dreaded malaria. She then
prescribed some drugs and told us to keep an eye on my body
temperature. I complained all the way to the chemist, "how can this be
since I haven't got a single mosquito bite?". We bought the medicine,
another fifteen dollars or so, and went back home. Interestingly
enough, as soon as I started taking the medicine she prescribed the
fever went away, and, touch wood, it hasn't returned since.

Another interesting event was my birthday. My cousin Rosa organised a
very nice dinner at her place, with lots of people including Ica and
Elsa. It was great fun, and the food was delicious - it's impossible
to decide on which dish was the best one. The night ended with a drink
at Chill Out, a very nice bar down at Ilha.
