#+title: Notebook of a Return to My Native Land - part 8
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil
#+HTML_HEAD: <link rel="stylesheet" href="../css/tufte.css" type="text/css" />

[[file:index.org][Back to chapter index.]]

Thursday, December 28, 2006

* The Long Wait

We arrived in Luanda on the 11th of December, a rather cloudy day. The
pilot circled above quite a few times, and, in perfect English -
perhaps with a faint hint of an Afrikaans accent - he apologised again
for the delay. As a prelude of things to come, we were stuck in a
queue and were waiting our turn. Eventually we were given permission
to land in airport 4 de Fevereiro (or 4th of February). For those who
were not born in communist countries, there is a long standing
tradition to name roads, airports and other important things after the
nation's key events. For instance, avenue 17 de Setembro (17th of
Setember) marks the death of the first president, Agostinho Neto - a
great man. And 4th of February was the beginning of the long standing
colonial battle, which then turned into a civil war. If you look
carefully you can still see this in Portugal, the last legacy of the
days when the communist party was in power: the bridge 25 de Abril
(25th of April, the day the dictatorship ended), the odd streets named
1ro de Maio (1st of May, worker's day).

The plane descended and cut straight through the thick cloud
cover. Luanda presented itself, like an artist waiting behind a
curtain. It had been a long wait. I don't know precisely when I left
Angola; I was young and all the papers we had about the departure have
long been lost, so now its the stuff of lore. It must have been around
1981, but I remember very little. A quarter of a century later I was
seeing the same sights, but instead of sad goodbyes this time I was
saying hello. Luanda lays itself in a long, low-rise sprawl. The
occasional high-rise pops up, and they are very high. From up above
you can see many paved roads and many, many musseques (slums,
bidonvilles; the Angolan Portuguese of the Brazilian Portuguese
"favela"). Musseques are organic things: they are born, they grow,
they reproduce, and, eventually, like all living things, they too
die. And they always go out with a bang, with the most troubling
spasms, involving huge amounts of violence. Near the airport there is
a musseque. It has expanded so that it now borders the walls and
fences of the airport. But, where the fences are more permeable, there
is an open gateway for enterprising kids. And so, as the plane dragged
itself to its parking spot, we went past kids playing football on the
tarmac - at a distance, not too close to the planes. There probably
are known territorial rules between the two worlds. The kids seem
happy. Behind them there are huge amounts of makeshift houses with the
colourful inventiveness that only the slum builder has, taking
whatever materials are available and finding uses for it that stretch
the boundaries of human imagination.

When we finally left the plane, we were greeted by the humid, very hot
air of the luandan summer. The 27 degrees on the thermometer felt like
at least 40. After a swift bus ride, we were taken to the main
terminal. The terminal denoted its age, with a few water leaks. We
were a bit apprehensive and didn't quite know what to expect, but we
had been warned by everyone that immigration people liked to make
things hard (the exact Angolan expression is "complicar"). As we were
walking past, we noticed we had to go to a stand with a chap
monitoring the yellow fever certificates. Thanks to the super
organised Shahin, ours were in order, up-to-date and pristine
looking. Lord knows I wouldn't have thought of that. But, if you take
one piece of advise from reading this blog, take this: make sure you
have your yellow fever certificate before you get into Angola or any
other country that requires it - hey, there are not that many
developed countries that have yellow fever. For if you don't, you will
be locked in a room awaiting vaccination; and when your turn comes -
it can be a while, days even - but when it comes, you will get
vaccinated there and then. Of course, even more important than being
vaccinated is having the precious yellow piece of paper that certifies
you as being vaccinated. We saw a woman (probably Portuguese)
frantically searching for hers, her hand luggage scattered on the
airport floor, all the while sweating and swearing to the official
"I've got it here, I'm sure it was here!". You can, of course, ignore
good advice and try to use the most advanced skills of desenrascanco
to get out of this one - we heard some great stories of desenrascanco
warriors - but, if you want my honest opinion, I say get the
vaccinations done and mind the certificate as if your life depends on
it. It does.

Once that was sorted out, we went to the main passport queue. The
queueing was nervous. Finally my turn came. Suddenly, at that point in
time, when I was standing on my own, just me and the immigration
official - as if a spotlight had been lit on the both of us and all
the airport had gone quiet - suddenly it hit me the amount of power
that these people have. This guy had all the power in the world. He
could decide that they needed to check my passport more thoroughly and
so lock me in; he could start asking questions as to why my passport
states I'm Portuguese but born in Angola - did I run away? Did I
commit any crimes? How did I get a visa without a Letter of
Invitation? All these thoughts were racing in my head. Pure paranoia,
of course, I kept on telling myself. In the end, he asked a couple of
questions but nothing difficult and waved me through. Then it was
Shahin's turn. The snag here was that I was told on no uncertain terms
to move on; but Shahin does not speak Portuguese (although she
understands most of it) and the immigration official did not speak
English either. So I kind of moved on but stayed behind the scenes,
literally behind the immigration official, and acted as the invisible
translator. It would have been funny were it not for the fear of God
we both felt. "So you're English, right? But you're trying to fool me,
you can't be English, you look like an Arab". Sweat drips down my hair
as I hear this. I search for the best, most adequate, most polite
Portuguese words I can think of. "Ah boss, she was born in England but
the family comes from Bangladesh". Long Pause. "Ah, of course, you see
you can't fool me. That's India, right? I knew she was not English."
And with this, he let her through.

When we got in to the luggage area, the usual chaos was ensuing. We
waited and waited, and just as our luggage was coming out, I heard my
name being called out: "Paulo! Paulo" (for those who know me as Marco,
most of my family calls me Paulo). I of course ignored it, can't be
for me. But turns out it was: my cousin Ica, with the help of his
never ending contacts, managed to get in to the luggage area and was
here to pick us up. It was great. We just got waved through
everywhere, and where before we saw only closed doors and sheer fear,
now there were only smiles and open doors. Ica seemed to know
everyone, from the security guards to the immigration officers to the
police officers. He worked the room as if in a cocktail party,
talking, praising, asking questions about the family, ensuring
everyone was alright. Eventually we got to the exit where my cousin
Rosa awaited us, in a nice car. I finally allowed myself to relax. The
long wait was over and we were now officially in Angola.

The ride back from the airport was a great metaphor for life here, as
all the core ingredients were out on display. First, the traffic was
horrendous. As we found out later on, this is pretty common in Luanda
and the roads are constantly jam packed full of cars. Second, unlike
in other countries, in Angola you don't just wonder how the other half
lives. Its right there, right in front of your eyes. People are
everywhere in the streets. Not many beggars, mind you, but many people
trying to make a living any way they can. Black faces that, at dawn,
overspill from the musseques into every conceivable space in the town
centre; and, at dusk, repeat the peregrination in reverse, hopefully
now with a little less merchandise and a little more money. Women walk
around, up and down the streets, routing around holes and traffic, all
the while balancing impossible weights on their heads and carrying the
kids on their backs - the trapeze artists in this great circus of
survival. The streets are full, brimming, throbbing with life. The
traffic in Angola is composed almost exclusively of three types of
cars: the blue and white candongueiros, Angola's name for the
universal mini-bus of Africa - the Toyota Hiace; the taxis, mostly
unmarked Toyota Starlets, distinguished only for their mashed up state
and their crazy, rally-like drivers; and, finally, the big shinny new
jeeps and SUVs. The later come in all shapes and sizes, and constitute
probably about fifty percent of all cars on the roads. Now, this is
amazing, considering that the roads are full of cars. Luanda is a bit
like an open air 4x4 auto show. You can see every model ever built
here, with huge emphasis on the latest and the greatest. I have seen
many cars in Luanda that I never saw before - either in Europe's
capitals or Africa's. And this is a great reflection of the state of
things: you either have a Prado or you fight the crowds to get into
the candongueiro. There's nothing in between. No one owns a Nissan
Micra. No one has a Ford Fiesta.

We got to Tia Linda's house, where, as we were told in South Africa, a
room had already been prepared for us. From an European perspective,
Tia's house is large, but otherwise fairly standard. All the mod-coms
are available, such as Air Conditioning. However, after backpacking,
the only way to describe it is as absolute comfort.

** Sketches of Modern Luanda

From "Chechnya" to the new Sonangol building, Luanda is a city of
contrasts. But my original impressions where perhaps a bit too harsh
on the country. After a few days of living here, one starts to
understand the city better. It does take a few days to be able to
start appreciating life unfolding around you as you walk. It is much
easier from a car - with someone else driving - but its very difficult
to observe while you walk. The main reason is the sidewalks of Luanda
are in a continuous state of construction. It is as if the entire
population of the city's sidewalks is simultaneously being worked on -
but no one is ever doing any of the work. There are holes everywhere
you go, reminiscent of Maxine's potholes in Ecuador. So, when you are
new to the city, you spend a lot of time looking at the
ground. Ridiculous amounts of time. It is as if your primitive brain -
the bit of you that knows how to walk without being instructed to lift
one leg and then the other - decides that the problems its facing are
far too complex for the simple algorithms it has learned in Europe and
so, washing its hands from it, passes over the control to your
conscious brain. This is why its impossible to observe, to maintain a
conversation or a train of thought while you walk - you need all of
your attention just to get by. There are a few sidewalks in a good
state, but these are almost exclusively near government buildings, new
company buildings or shinny new houses. The remainder of the sidewalks
are filled with holes. And then there are the electricity cables. The
first few days, as Ica was showing us around town, he warned with a
serious tone: "when the rainy season comes, make sure you avoid all
the puddles. They are quite lethal, as underneath there can be a live
electricity wire. You step on one of those, and that's the end of
it.". The other thing that takes a major toll on your brain's
processing power is the traffic. Since many sidewalks are unwalkable,
and many of those which aren't have so many cars parked on them as to
make them unwalkable, you are frequently forced to go into the
roads. This, in Luanda, is a serious undertaking, never to be
underestimated. Not only do you have to face high-speed candongueiros
and taxis, but the average Luanda driver in his or her's 4x4 also
thinks they're Michael Schummacher. In fact, they have to. Driving
here is a continuous battle against traffic jams, and people who are
able to sneak in the smallest gaps, park in the impossible spaces,
cross intersections filled with cars going at high-speeds and drive at
impossible speeds in narrow roads enjoy a huge advantage over those
who can't. This evolutionary pressure was so incredibly successful
that the vast majority of Luanda drivers are experts: you are either
an expert or you don't even dare to drive here. Which brings me back
to sidewalks. You cannot imagine how difficult it is to cross the road
around here. When the cars are in full motion, it roughly resembles
trying to cross Silverstone during an F1 Grand Prix. Except there's a
lot less F1 cars in a Grand Prix than in the average Luandan road. I
almost got into an accident a few days into our stay. I checked both
sides, and all cars were safely locked in a massive traffic jam. We
then proceeded cautiously to navigate our way across. At the very last
bit, a motorcycle just went past at a high-speed and almost knocked me
out. I thanked the ancestors for that warning sign and since then have
checked four times every time I cross the road.

Whilst there isn't at the moment a major push to sort out the
sidewalks, the story is quite different when it comes to
buildings. Luanda is a large building site, with quite a few finished
products. There are many cranes filling up the skyline, and almost
every new building is high-rise. Twenty stories and more are pretty
common. Some of the buildings look really impressive. Also, almost all
state buildings have been refurbished and they look quite impressive
too. Many a time we've been past huge colonial-looking buildings,
thinking they're some residence of a really wealthy person only to
find out its the maternity unit, a local hospital or the head offices
of some ministry. However, there are also many old, decrepit
buildings - "Chechnya" is perhaps the best example of this. (Let me
rant a bit here: it always struck me how people name bad places in
their country after what they perceive to be bad places in distant
countries. Its the ultimate insult, and, to me, its always more
insulting for those doing the naming. For instance, there's a
notoriously bad prison in America called Angola. Perhaps, because
these places are faraway, one thinks that they are so much worse off
than us. I remember that, at one point in the early eighties, my 'hood
in Portugal used to be called Shanghai. How offended the wealthy
Shanghaiese must feel now). So, in this long standing name-calling
tradition, the Kaluandas (inhabitants of Luanda) named one of their
worst construction disasters after that famously disputed Russian
region. The story of the building is not entirely clear but, according
popular legend, it appears the construction was done in an area where
the soil is no good, and so the building is sinking. So, long ago, the
government embargoed the building and construction halted. However, at
the time there wasn't a push for real estate like there is now, so
nothing was done and the building was left as is - very much like one
we've had downtown Barreiro, Portugal, for the last twenty or so
years. But, the Kaluandas, being much more resourceful folk than the
Barreirenses, decided that such a lovely piece of real estate could
not just be left to rot and finished the job, musseque style.

However, although one begins by having a markedly negative view of
modern Luanda, on hindsight, its impossible not to have great
optimism. Lets do same name-calling: Luanda is not Monrovia. (Forgive
me Liberia; I've never been there, but I need something to compare
against; odds are most readers never been to Monrovia either but also
share think it's as close to hell on earth as you can get. I remember
a quote during the eighties about the war in Liberia, when Angola was
a particularly nasty place, that went along the lines of "Liberia is
like Angola gone wrong". That always made an impression on me). And
yet, the civil war in Angola raged for over thirty years. In Angola,
things are happening. Confidence is in an all time high, inflation and
the Kwanza are under control - if the prices are somewhat high, a
topic we'll return to later - and there is a huge amount of
development going on. The fact that there is a pretty nasty Luanda out
there, and that most Angolans live in slums is not the amazing thing;
that is to be expected, given the context. We all know the atrocious
job the colonising nations did, at all levels. By the time the
Portuguese left, less than 5% of the population had access to high
schools. This disastrous management was compounded by an even more
atrocious job done by the government, due to both internal and
external factors. Corruption is rampant. By all accounts, Angola
should be, at this juncture in time, one great, massive musseque. But
its not. Its a vibrant, busy, out-and-about sort of place, with lots
of foreigners here. The Portuguese youth and the Angolan diaspora are
migrating in droves. I always thought of oil and diamonds as the
"devil's blood" and as a curse that, by itself, generates
underdevelopment. Standing in Mutamba, in the centre of town, one has
to admit that, although the vast majority of the oil and diamond money
is being siphoned away and most people don't get their fair share, the
country as a whole is, at present, a lot better off for having it. As
Miguel put it a while ago, the Angolan economic train is moving at
full speed. This is only possible due to the huge wealth generated by
the oil and diamonds.

One of the chaps we met here, Paulo, put it in a very descriptive way:
"You think things are bad now?! Things are great! there are jobs,
things are happening. You should have come here a few years
ago. People used to queue for hours on end for everything. It was so
bad that, at one time, when you saw a queue you went and immediately
joined it. You wouldn't even think, just run and join the queue. You
didn't know what people were queueing for, most people in the queue
wouldn't know either. But you'd queue just the same, because there
were not that many things available you could buy, and if people were
queueing, there must be something being sold. Sometimes you got to the
end of the queue and the item being sold wasn't something you could
use, like hygienic towels or something. But it was sheer desperation,
the fear of not queueing and missing out.". In fact, one of the few
things I remember about Luanda when I was a kid were these long
queues. I just remember sitting with my mom and queueing, for hours on
end. Now the queues are over, for the most part. Ironically, you still
have to queue for the fuel. But all the goods are available,
supermarkets are plenty and well stocked. The new problem is cost:
things are very expensive.

| [[file:part_7.org][Back to previous chapter]] | [[file:index.org][Back to chapter index.]] | [[file:part_9.org][Forward to next chapter]] |
