#+title: Notebook of a Return to My Native Land - part 10
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil
#+HTML_HEAD: <link rel="stylesheet" href="../css/tufte.css" type="text/css" />

[[file:index.org][Back to chapter index.]]

Friday, January 26, 2007

* Benfica Market

Benfica, like many areas of the greater Luanda, is not a particularly
nice place. There isn't much to it, really, apart from the main road
and the thousands of makeshift houses, scattered in all manner of
improbable shapes, layouts and compositions. However, Benfica is home
to a smallish market that specialises in African art, making it a very
popular place amongst foreigners - a claim to fame that few musseques
have. In fact, one can even go as far as saying that this market is
created by foreigners, for foreigners. This is because a large number
of the craftsmen exhibiting their wares are not from Angola but from
other parts of the continent such as neighbouring DR Congo, or even
from further up north like Mali and Senegal, and many of the items out
on display seem clearly to have been imported rather than crafted
locally. The punters, mostly white and mulatto, but some black faces
can be spotted too, are most likely members of the diaspora or
foreigners working for one of the many multinational companies present
in Angolan soil. We went to the market with Elsa and Rui, the main
excuse being that Elsa wanted to buy some art for the house, but in
reality, we all know that women just love markets.

The market itself is a small, unofficial affair, laid out in that
characteristically narrow way that almost all informal African markets
are. The rows of stalls are very close to each other, and are densely
packed with merchandise. The remaining gaps are filled with people,
many of them vendors and a few buyers. This results in dark, narrow
alley-ways piercing into the market, and then across it, and give it a
somewhat menacing look at first. One soon gets used to it though, if
not by our own devices then by the insistent calling of the vendors,
almost all men: "Amiga, Amiga, aqui!!". Marketers are successful
predators, so they know to always target the vulnerable - in this case
the girls. When one does venture into the narrow corridors, stall
after stall packed with different kinds of objects greet you. But
don't delay yourself too long on any one given stall - long here being
measured in tens of seconds - lest the vendor think your interested in
one of his goods. For if he does, he'll chase you down the market,
continuously enticing you, continuously negotiating the price, forever
making sure you are aware of the incredible deal you're missing out
on. The items for sale in this section of the market are mainly wood
carvings, but incredibly there's also a lot of ivory carvings
too. Further afield there is another section specialising in paintings
of all sizes, not quite as large as the carving section, but with fair
variety. In between the two is an area with various other types of
craftsman such as the mosaic tiles Elsa was after, and has been after
unsuccessfully for the past five years. Behind all of this, hidden by
a large corrugated iron fence, is the food hall. Here grilled fish and
other delicacies are sold, and some kitandeiras (or street sellers)
sell diverse foodstuff. The food hall is, unfortunately, as informal
as the rest of the market, so you can eat there at your own risk. Not
advisable to foreign stomachs, basically.

Whilst it is worth visiting Benfica's market, it has to be said it is
somewhat disappointing. First, many of us were actually looking for
some authentic Angolan art, and there was very little of it
around. Most things on display belong to that fuzzy category of
"African Art", the sort of thing that you see in markets all over
Europe and all over Africa. The usual masks and statues, the paintings
with people wearing straw skirts and dancing to the rhythm of the
tan-tan. I recall Naomi Klein complaining in No Logo of the
manufactured "world culture" created by people like Coca-Cola and MTV,
which resulted in the homogenisation of teenagers all over the world:
the baggy trousers, graffiti-like t-shirts, hip-hop or rock music. The
same globalising trend left no area of African life untouched, but its
art was affected mostly from within. No multinational company was
involved in the process; for a change, Africans seemed to have done it
all by themselves. The result is this polymorphic "African" art that
belongs to no country but takes traits of a few, and just like the new
global youth culture, it is "local" everywhere. This African Art, by
trickery or merit - the verdict is not out yet - steals the oxygen of
any local art that attempts to emerge and is extremely popular with
tourists looking to give that "African" feel to their houses or
establishments. There were very few differences between what we saw in
Benfica and the goods available in Swakopmund's market, Gambia or the
Cape Verde islands. I'd wager that very similar items are available in
Wembley, London or in Feira da Ladra, Lisbon. In fact, the problem has
become so severe that the few remaining local tradesman use their
nativeness as a competitive advantage and sell themselves as providing
authentic local art - as opposed to "these foreigners, selling their
stuff as if it was our own". Of course, the foreigners were quick to
catch on, so they'll tell you exactly the same, except that, in
Angola, one can easily tell them by their accents; at any rate, the
real Angolan sellers will probably be peddling the same type of
goods. The second thing that was disappointing was the amount of ivory
for sale. Literally every other stall had items carved in a shinny
white material which appeared on sight to be ivory, and was sold as
ivory by the merchant, up to the point when you asked whether it was
legal to buy it and take it on the plane - and suddenly the ivory
transformed itself into another material altogether, unspecified, but
assured to be as close to ivory as it gets. Crazy, the things science
is able to come up with these days, hey. Some stalls even specialised
solely in these items, to the exclusion of everything else. The third
negative aspect of the market were the prices. In a way, this had to
be expected since everything in Luanda is expensive as a norm anyway,
and to make matters worse, foreign buyers are always prepared to pay
over the odds. Still, one always expects to find a bargain. As far as
we could ascertain there were none to be found, and even haggling with
the sellers - which Rui did with extreme expertise - yielded no
breakthroughs. This is a clear indication that somebody else must be
willing to pay these horrendously high prices. In the market's
defence, one has to say that Angola is not, by any stretch of
imagination, a tourist destination, so a more diverse offering would
not make any economic sense. And vendors are catering for what punters
buy, so there must be a lot of people still buying ivory out there.

After some browsing we decided to inspect the food stalls, but since
both girls have very sensitive stomachs and were entirely unwilling to
eat there, we ended up going to the nearest restaurant, Girasol. This
is just up the road from the market, in the rest area of the Sonangol
gas pumps. Unfortunately, very much in keeping with the theme, prices
were extremely high: the only available meal, a Brazilian rodizio
buffet, was 3400 kwanzas per person - over 40 dollars. This did not
include drinks, desert or starters. The food was alright, but not
quite good enough to justify the price tag. We heard since that many
Angolans actually make the most of their 3400 kwanzas, getting there
for lunch and not leaving until almost dinner time, eating all the
while from the buffet.

After lunch we returned to the market and haggled some more. In the
end, I was the only person to buy something: an Angolan white top with
Mantorras on the back, the team's main striker. (Yes, the one that
never plays.) It set me back around 1000 kwanzas after some haggling,
which I was quite proud of since I hate shopping in any shape or form
and, as a rule, I tend to just pay what people ask and run out of the
shop as quickly as possible. (Come to think of it, my lightning fast
exits from shopping malls probably raise a lot of suspicion, but I've
never been stopped and searched in England.) In addition, I was also
quite happy about the final price because its roughly eight times
cheaper than what I had paid for the official top during the World
Cup. Who said there were no bargains to be had? This one was a fake of
lower quality, of course, but still.

** The Long Walk; Goodbye and Hello

As the new year dawned, time came for Elsa and Rui to return to
Portugal. Just before departing, they still managed to find a bit of
time to give us a quick tour of some interesting places in Luanda we
hadn't yet visited. Ever enterprising, we decided to walk from
Kinaxixi to Maianga and meet up with them at their house. This is a
fair but not unreasonable distance to walk, at least as far as the map
is concerned. To be perfectly honest, I don't really know how I
managed to convince Shahin to walk up since she - and everybody else I
know, now that I think of it - is acutely aware of my special
abilities in getting lost. But, convince her I did. I'll spare you the
suspense and go straight to the conclusion: for some unexplainable
reason, totally unrelated to my person, we managed to get lost. I
mean, we were not lost as such, we just didn't know the exact turns to
make, which for Shahin and most women is equivalent to being lost. Me,
like every other bloke with an ounce of self-esteem, I know that given
enough time you'll eventually start heading down the right road and
before you know it, your target lies ahead of you. Its just a matter
of time. Asking for directions is for wimps. Problem is, the rainy
season in Angola is hot, damned hot, and to make matters worse, we
left the house an hour or so before the hottest time of the day. After
a good hour of walking round, I started to notice the menacing groans,
moans and cursing coming from behind me, which seemed to continually
increase in loudness and menacingness and displayed an obvious
correlation to temperature and elapsed time. I was forced to admit
that I was a little unsure of the exact road on which to turn. Like,
half-an-hour ago. The response sounded so inhuman - so much contained
rage was involved - that I immediately decided to lose all my street
cred there and then and ask for directions. We asked a few times, but
the passers-by either didn't know the best way to get there or they
gave us directions in that vague way that only Angolans can - "go like
that a bit more, turn like this, its there!", all the while pointing
and gesticulating. "But is it the first turn or the second?" we would
ask, only to hear an angry response "No! Go like this!!", followed by
some more gesticulation pointing in the general direction ahead or
behind you. Everyone we spoke to, even those unsure of the exact
location, were invariably convinced we were going the wrong way. We
ended up going a good twenty minutes backwards only to find out we
were, indeed, going on the right the direction all along. Eventually I
decided to ring Rui - an act that was repeated a good twenty times
before the hour was over - and he gave me some clues as to which way
to go. Unfortunately, as I think I've mentioned before, Luanda's
streets are not named. That is, they have official names, but since
there are no signs up in the actual streets, no one, not a single
inhabitant of this city, knows the real names of its streets. Ask
them, as we did, where Avenida Lenine is or where Rua Agostinho Neto
is and they will look at you in disbelief. All directions are given in
terms of reference points: "turn at Chevron's building", "just before
you reach the Portuguese Embassy", "turn before hotel Tropico", "go
towards Radio Nacional". Almost all these reference points are
meaningless for foreigners. After all, unless the reference point is
incredibly obvious, and most aren't, you don't know when you've gone
past it. As we were stumbling across town we somehow managed to bump
into the church of Sagrada Familia, which was just as well as that's
were I was baptised, many, many years ago, and that's where the only
proof of my Angolan citizenship remains - at least one hopes so. If we
knew anything about Luanda's layout, all warning bells would have
started to ring as soon as the church became visible. Fortunately, we
didn't. As it turned out, the path we took is quite possibly the
longest possible path joining Kinaxixi to Maianga, even if ones
excludes the twenty minutes up-and-down-hill detour. We finally
reached our destination a good two-and-a-half hours later, in the
blistering Luandan heat. The funny thing is, afterwards, Elsa and Rui
showed us the "other" way, and not only is it easier, almost all the
way straight ahead, but it takes probably thirty minutes. Shahin
somehow did not see the funny side. Oh well, at least we got to see a
lot of the city, I say.

Once we rested and recovered, we set off to Wimpy's, one of the very
few fast food places available in Angola - no, MacDonald's hasn't made
it here yet. Prices in Wimpy are fairly reasonable for Luanda, and a
meal can be had for around 1000 kwanzas. After eating our burgers, we
had copious amounts of ice cream, which whilst not the best in the
world was of a fairly decent standard. Rui then took us to the
sights. This included another trip to Fortaleza, now inside the
comfort of the jeep. Unfortunately yet again we didn't have our camera
on us, so we'll have to return a third time to take pictures before we
go. Afterwards we descended towards Bairro Azul, Rui's old
neighbourhood, which we dutifully inspected and listened to Rui's
reminiscences. There's always a special feeling when you return to the
places of your childhood. Then it was Cidade Alta's turn. Cidade Alta,
of which we knew only DEFA's headquarters, sits high above town. Here
is where most of the offices of the ministries are, as well as the
presidential palace. It is such an important place you are only
allowed to stop there to drop passengers and even then only for the
briefest of periods. Whilst driving round, with the usual carelessness
of the Angolan - "e' tudo nosso" they say, "its all ours" - Rui
managed to take the wrong turn and head towards the presidential
palace. The flag was up, indicating Jose Eduardo dos Santos, or Ze Du,
was in. Two guards standing at the door noticed our mistake within
seconds and one of them, springing into action, came towards
us. Nobody else other than Shahin noticed this, but the other guard
actually cocked his gun. We were told in a very firm and clear manner
that this was a restricted access road and we were to turn back
immediately. Obediently and apologetically we turned back and
descended towards town, this time via the other side of the hill that
leads into Cidade Alta. Here one can see many grand colonial houses,
in varying states of decay. Some of them have been recently renovated,
but many are still in the hands of squatters and are in a messy,
musseque like state. All of them have important proprietaries though,
and none are up for grabs. Not unless you have half-a-million dollars
or so lying around. Here, like in most prime areas of Luanda, the
government is moving in to perform a clean up operation, removing all
the unwanted musseque citizens and relocating them to other areas of
town. As pretty much everything else around here, this process is not
done in a nice, orderly manner, and there are many well founded
complaints from humanitarian organisations. Nevertheless, I think few
people disagree that something needs to be done. Some of these
musseques - like Praia do Bispo - are sitting on prime land for real
estate development, potentially worth hundreds of millions of
dollars. Such revenue is more than enough to create decent housing for
the relocated inhabitants. However, the latter rarely seems to come to
fruition, probably due to the influence of the usual interest
groups. With election time looming - or forever looming, should I
say - its in the government's best interest to look after these
people, at least in some small way.

Piscinas do Alvalade - the Alvalade Swimming pools - were our next
destination. It was here that myself and Elsa had our first swimming
lessons, many moons ago. They now have a lovely esplanada, famous for
its milkshakes. Judging by the quality of the avocado milkshake I had,
the fame is well deserved. They also have very good snacks, in
particular prego no pao (stake in a bun, literally). The day was
concluded at Walter's house, a cousin we hadn't met before. Walter is
a TV director, with his own company, but with very close links to the
state's TPA. He is an incredible character and the couple of hours we
spent on his presence where absolutely hilarious.

This was the last day we spent with Elsa and Rui. The time we spent
together was excellent, and it was with great sadness that we waved
goodbye to them. After all, this was the first holidays I spent with
Elsa since our teenage years. Unfortunately, most people have jobs to
go back to, and so their holidays must, at some point, come to an
end. Its hard to imagine from where we stand, but one day this
adventure will have to end too.

On the positive side, just as we were saying our goodbyes I got a call
from an unexpected source: Lau and Leonor had just arrived in town.

** On the Road to Benguela

With Elsa's departure, we began to feel more and more restless. Luanda
is not a friendly place to people without a vehicle; it makes you feel
a bit like you're on house arrest, and each outing requires more
planning than a prison escape. Its just too damned hard to get
anywhere without a car. Besides, we initially wanted to spend as
little time in Luanda as possible, a plan that failed miserably: we'd
been stuck in the capital for over a month. The situation was
desperate. It was time to move on. But, like so many things in Angola,
its much easier said than done. For starters we didn't have our
passports on us since we were working on getting the visa extended (a
topic we'll cover extensively on a subsequent chapter). Whilst the
DEFA people insisted you can travel using the receipt they supply, we
simply could not bring ourselves to believe that life would be that
easy, and no one of authority wanted to confirm this statement -
including the Taag Airline people. There were also some more
philosophical reasons: you don't see much on a plane; you just get
instantly transported from one place to another without being given a
chance to understand the context in which these places exist, without
seeing the smooth transitions, the slight changes in the landscape,
the beginnings of that small river that becomes big and feeds the
city. And that is the whole point of long term travelling: to
understand. So we started investigating the possibility of getting
somewhere overland. The most likely candidates were Benguela and
Lobito, the sister cities in the province of Benguela, about half-way
down the Angolan coastline. The capital of the province is Benguela,
but Lobito is an extremely important economic centre since it is home
to the Lobito Port, one of the biggest deep water ports in
Africa. Elsa's auntie Nene lives in Lobito, where she teaches at the
private university Lusiada - so it seemed like the perfect
place. Initial contacts were made and we quickly ascertained that
finding cheap accommodation in Lobito would not be trivial. Nene is
housed in the university halls of residence, and staying there was not
an option. And all her contacts didn't seem to come up with an
affordable hostel, catering for two poor backpackers. However, we had
a wild card up our sleeves: both Lau and Leonor are from Benguela, and
have family there. Through Lau's contacts we found out that his
godfather's sister had a little hostel going, for the extremely
reasonable price of 40 USD per night, including television and air
conditioned. We waited a while longer to see if something would turn
up in Lobito, but nothing did, so we asked Lau to confirm our stay at
the hostel. Clearly, the operative word in organising things in Angola
is not "Internet"; its "Contacts".

Now it was time to sort out transportation. We had conflicting
intelligence with regards to the buses to Benguela. On one hand, one
of our contacts was convinced that the buses were departing all day
long from Rocha Pinto, an infamous musseque. These were candongueiro
like buses that waited for customers and left when full; no time table
was available. On the other hand, our cousin Rosa was convinced that a
fairly organised bus service ran from Multiperfil, or thereabouts, and
this service had a timetable, air conditioned and everything else one
expects from modern transportation. However, since none of the
contacts had actually been on a bus, they didn't know for sure how
things worked. In fact, everyone we spoke to was extremely surprised
with our decision to go by bus. They first displayed some incredulity:
"you're joking, right?! do you know how these buses are like?!". All
tried to change our minds, and all had lots of advice on how
travelling by plane is faster, safer and actually not that expensive;
100 dollars or so would buy you a ticket. Once they saw that we were
actually seriously considering going by bus, they would explain the
state of the roads. "Well, I suppose the road to Benguela is one of
the good ones, probably the best to travel on... And if you're not
taking too much stuff, you shouldn't have to worry too much about
being robbed...". Thus encouraged, we decided on this course of
action. But before we could know for sure, we had to go on a scouting
mission to the bus terminals and see the vehicles with our own eyes,
to figure out the missing details such as whether you needed to buy a
ticket beforehand, the exact location of the terminal and the
timetable - if one did exist.

With Elsa's departure, our mobility was greatly reduced, so we had no
option but to venture further inland into the candongueiro transport
system. While we were extremely confident on travelling from Mutamba
to Ilha, either by Taxi or Candongueiro, we had little experience on
any other route. This is a much more severe problem than what it seems
to the untrained eye. You see, the whole infrastructure is designed
for locals who know what they're doing. There just isn't a
candongueiro central information point, explaining all the routes and
detailing the most optimal way to get from A to B. People who ride on
these things know them inside out, nobody needs external
information. The difficult bit is attaining membership to this select
club. Our intelligence pointed out to a candongueiro that did the
route from Mutamba all the way to Rocha Pinto, precisely what we
needed. However, we didn't quite know the exact spot in Mutamba where
the stop was, and this is no small place - particularly when there are
dozens of candongueiros wizzing past in all directions. And since the
cobradores (or ticket inspectors) in the candongueiros just shout
reference points, one did not quite know how to make sense of what
they were saying. "Angolense!!" - does that go past Rocha Pinto or
not? To make matters worse, cobradores and candongueiros in general
are always in a rush; its impossible to maintain a conversation with
them for more than twenty seconds. You can only ask something like "do
you go to Rocha Pinto?" and get a yes or no answer. That is, if they
manage to understand what you're saying. And herein lies another of
the great difficulties facing the diaspora. No one, not a single young
Angolan, seems to understand what we say unless we speak r_e_a_l_l_y
s_l_o_w_l_y and with no slang whatsoever. Forget about looking cool,
its much more important to be understood. I just don't get it, its
like we're speaking in a totally different language - except we use
almost identical vocabulary, with words like kota, kubico, kamba, bueh
and so on. Don't get me wrong, when they talk back to us, good lord,
we can't understand a word of what they're saying either. So we have
these hilarious conversations with no meaning whatsoever:

- "What is the price?",
- "Destination is Sao Paulo!"
- ...

It can take quite a while to obtain meaningful information. And then
there is one additional complication to this already extremely complex
picture. There are not that many non-blacks who travel by
candongueiro, and those who do stand out like a sore thumb. This, in a
place where unemployment is rife, and where non-black people are seen
bu default as rich, is a sure recipe for daylight robbery, unless you
appear to be streetwise at all times. And its hardly streetwise to
stop in the middle of one of the busiest intersections in town and ask
for directions to one of the most notorious musseques of the capital,
speaking in a language that no one else understands. So you can
imagine our uneasiness. We tried a couple of places in Mutamba, and
tried really hard to listen to what the cobradores were saying, but to
no avail. We then asked some locals, again with no luck. Shahin was
convinced the stop was just up the road, but I started to chicken out
and decided the best bet was to go for plan B. There was a second
route to get into Rocha Pinto which required changing. And we knew
where the first candongueiro departed from; we were standing right on
the stop to the airport. When the next available candongueiro
appeared, we jumped in.

Once you're in, you actually blend in with the crew fairly
quickly. The stares cease. But then the worry is that you miss your
stop. After all, the cobrador only tends to announce the final
destination; the stops in between are up to the passenger. It stops
anywhere in its route, all you need to do is signal your
intention. But you need to know where you want to stop. Or you need to
ask the cobrador to let you know when your stop comes - something you
might just want to avoid when you're about to be dropped in one of the
dodgiest parts of town. Fortunately, to our immense relief, our last
stop was actually the end of the route. The airport is a large
candongueiro interchange, messy, full of people and covered in
mud. There one can hear the cobradores shouting almost all the names
of all neighbourhoods in town. We had to ask the locals for some help,
and, after a couple of tries, we managed to find some nice people that
gave us lots of useful information. One thing we found out is that
most elder people - elder being over forty - understand fluently the
diaspora's Portuguese and are actually really friendly. Almost
everyone we met went out of their way to make sure we were all right,
and some even did it literally by giving us their seats on a hard to
come by candongueiro. Conversely, almost all youngsters were rude,
un-understandable and in general totally useless - this is valid for
both boys and girls.

Armed with the additional help from our "Mais-Velhos" (elders, in
Angolan Portuguese), we easily found transport to Rocha Pinto and
jumped in. This time we had no excuse, we had to get out before the
last stop. Luckily, some of the people who had heard us asking for
information were also in the candongueiro - a couple of middle aged
women. They started chatting to Shahin - its rare that we sit next to
each other, you sit where there is space and that can be anywhere -
and she had to pretend to understand what they were saying without
speaking out loud in English. Soon enough we went past a set of buses
stopped next to the road, and these really appeared to be the ones we
were looking for. A quick exchange with the women convinced me we were
in the right place, so we jumped off. In the midst of all the action,
we didn't quite realise what we were doing. As soon as the
candongueiro moved away and we were left standing in the middle of
nowhere, and at that point absolute fear just overcame both of us. We
had just been dropped off in the middle of one of the harshest
musseques in town, the only non-blacks for miles, and everyone was
staring at us point blank. We had been to musseques before, but always
inside the safety of the car, always with doors locked and ready to
move on if trouble started. This was different, there was nowhere we
could move on to, not unless we got back into a candongueiro. This
paralysis lasted for a split of a second, which seemed like forever,
but then self-preservation kicked in and we immediately started to
walk confidently towards the buses. There really were buses of all
types, but most of them were just big candongueiros and didn't inspire
much confidence for such a long journey. We were desperate to avoid
deathtraps, and overall the buses on offer were extremely
disappointing. The best buses were not going to Benguela. What the
crappier buses didn't have in quality, the cobradores made it up with
persistence: as soon as you went past some vehicles, a swarm of
cobradores would instantly bombard you with information, telling you
that their bus was the best and ready to leave, only waiting for you
to get in. They'd follow you for a fair bit, continuously pitching
their product over all others. One cobrador followed us for the length
of the road, but I think it was mostly due to curiosity - Shahin gets
stared at by almost everyone, there aren't that many Asians
around. Prices started at 2500 kwanzas, extremely high for the
vehicles in question.

Thus disappointed, we decided to move on and go to Multiperfil. Since
we didn't know where this was, I thought the best bet was to keep on
walking - hey, how far can it be, right? The end of the road was still
at some distance, but not too far, hundred metres or so. We walked
past all the street vendors and bayaye, past the kids bumming around,
past the men carrying heavy loads in their wheelbarrows and past the
old people trying to make a living out of whatever nothing happens to
come by. Whilst we were afraid of being robbed, the truth was we had
nothing on us, nothing that could attract attention - other than our
skin colour, of course. The one hundred or so metres seemed to last
for ever, dodging rubbish, people, kids, telling vendors we were not
interested in whatever they were trying to sell us. After a while it
became clear that Multiperfil was not up the road, so we had to again
ask for information. We chose a particularly innocuous spot to stop, a
place were people were already waiting for candongueiros, and waited
for a suitable candidate. After a while, a middle aged man came and we
asked if it was possible to walk to Multiperfil. He laughed at the
idea and helped us get on the right candongueiro. We still had the
slight problem of not knowing where our stop was, but after so much
excitement we lost all fear and asked people inside for
information. The candongueiro dropped us around the corner from
Multiperfil, which until then we didn't know what it was. Turns out
its a very large eye clinic. The bus terminal, however, was nowhere to
be seen. We asked for some information in the local supermarket where
Mr Sayeed, probably the only non-black, non-Portuguese for miles, told
us in a broken Portuguese that the buses stopped right in front of his
door but we had just missed one. This was extremely disappointing, we
were expecting something a lot more organised than that. We left the
shop - not before being robbed blind by Mr Sayeed on the bottle of
water we bought - and waited outside. Time went by, and nothing
happened. We decided to double-check the information provided by Mr
Sayeed, only to find that it was totally inaccurate. There was indeed
a bus terminal up the road. We walked in the direction indicated, less
than two hundred metres, and a terminal (in the Western sense of the
word) appeared. The company running the buses is SGO (also known as
Interprovincial). They didn't have any more tickets, but if we turn up
early in the morning, around 5:30 or so, we should be able to buy the
tickets and travel to Benguela. Prices were similar to the
candongueiros, 2400 kwanzas, but the buses looked a lot more
reliable. Air con was dependent on the vehicle, we were told, but it
was most likely not going to be available. Journey time was not
known. Best ask the driver for some estimates. The scouting had been
completed successfully.

Returning to Mutamba was a much easier mission, since there were
candongueiros in Multiperfil that went straight there. We boarded one
and got dropped just behind Mutamba, near Papelaria Fernandes. This is
the stop for these candongueiros, and Shahin's intuition had actually
pointed her in the right direction earlier on, had I only listened to
her. We walked up from Mutamba to a local bar, where we had some
really cold drinks in the esplanada - I had a thoroughly deserved
draught Cuca, the Angolan beer of choice. Now all we had to do was to
get to Multiperfil at 5:30 in the morning. Lau very courageously
volunteered to drop us off, and this was a massive win as I don't
think we would have been able to make it otherwise. We still had some
fun in the morning, going back to Rocha Pinto to make sure there
weren't any other, more modern buses, but there weren't, so we ended
up just going to Multiperfil, buying the tickets and boarding the
bus. Very unfortunately our troubles were far from over. The seats on
the bus were numbered, and we got given those right on top of the
wheel, with absolutely no leg room - even a five foot person would
have struggled. To make matters worse, we had no room on the overhead
compartments so we had to keep our bags on top of our legs for the
duration of the journey. We were not the worse ones though, as some
people shared their seats with two and three kids - you pay on a per
seat basis and kids don't have to pay. Air conditioned (AC) was
certainly not available - didn't look like it ever was on that bus -
so we had to stick with the CA (Corrente de Ar in Portuguese, or Air
Current; i.e. open the windows). Most passengers were of the decent,
honest, working people sort, with the exception of a few youngsters;
just as luck would have it, these were right around us: in front, to
our right and behind us.

When we asked the ticket inspector about the duration of the journey,
he said it was very hard to give exact timings but he thought we
should be in Benguela before two o'clock. Departure time was going to
be punctual, at six o'clock on the dot. The bus did depart roughly on
time, and when we left the terminal, all passengers were neatly
seated. However, things started to change as soon as we moved away
from the terminal. The driver, once freed from the strict control of
the head office, started to supplement his lowly wages with additional
income on the side. This works as follows: people ask for the bus to
stop, just like you would with a candongueiro, at which point the
driver tells you the bus is full - but if you're able to handle it,
well, there are standing places available. These "seats" are cheaper
and don't go through the books. The journey continued in this
haphazard manner, stopping every so often in inner Luanda to pick up
passengers, at which point the crowd would start cussing - "we ain't
getting there today!", "come on!". Eventually the driver filled the
corridor with people to his satisfaction and the Luandan traffic was
left behind. The route we took was the same we did when visiting Cabo
Ledo, except this time we went past it and kept on going. Three or so
hours into the journey a strange smell of burnt rubber invaded the
bus. We couldn't quite figure out what it was for a bit, until the
driver decided to stop and inspect it. The bus had a puncture. The
operation that followed it was remarkable. All the kids and women left
the bus and sat by the shade on the other side of the road; all the
men and boys went to help out the driver in changing the tire. They
all seemed to be experts in tire-changing, and everyone knew exactly
what to do. In less than thirty minutes the old tire had been replaced
by a new one, and it was securely tightened by a group of able young
man - including the troublemakers surrounding us. Yet again I managed
to clearly stand out from the group as I had absolutely no idea on
what to do, so I decided to keep quiet and observe the proceedings. We
were again on our way. The bus then reached a small town and was
immediately assaulted by all types of sellers, shouting their wares:
"Gasosa, Gasosa!!", "Bolacha, Bolacha!", "Banana, Banana!!", "Ginguba,
Ginguba!!". Money exchanged hands through the windows, food was
purchased and consumed there and then, all this without the passengers
having to leave their seats. The resulting rubbish was mercilessly
thrown out of the window, much to our dissatisfaction and general
cringe. Four hours or so into the trip and we reached Sumbe. Here the
driver made a "quick" break for lunch and toilets, fifteen minutes or
so. These were, obviously, in units of Angolan Time. Over an hour
later we finally drove on. However, the road that had been our
faithful companion until then... disappeared. Yes, that's right, up
till that point there was tarmac on the road - some holes here and
there, some really bad parts, but tarmac was always present
nonetheless. From Sumbe onwards the road is best described as, well,
as being off-road really. Every so often there is a stretch of a
kilometre or so of tarmac but its then followed by twenty or more
kilometres of dirt tracks, full of huge holes. This remaining stretch
of the journey is absolutely dire. There is only a bit of respite when
one stops for a short break in Canjala, a lovely lush place in the
interior, so green it could be Vietnam or Cambodia. The Angolan
interior is full of such greenery. But it was hard to appreciate the
sights in such a confined space, unable to move due to both rucksacks
and lack of legroom, and general tiredness caused by waking up so
extremely early. It was a trying journey. Every so often we would look
at each other and just laugh at the ridiculousness of the
situation. You looked out of the window and all you could see was this
long, never ending road, surrounded by greenery on both sides, chasing
the horizon and ending far, far away. The road just didn't seem to
have an end. Every so often a candongueiro or a jeep would overtake
us, or a truck would move slowly in front of us, and the whole bus
would get filled with fine, powdery dust. The entire bus population
would then simultaneously close their windows, only to open them up on
the first chance we got since the heat was oppressive.

Around eleven hours after departing from Luanda, we reached
Lobito. Many of the passengers and their loads left the bus, much to
our satisfaction, allowing us to have a little bit more of
space. About an hour later we reached Benguela, taking a grand total
of twelve hours. As we left the bus we were immediately assaulted by
an army of taxi drivers, in Benguela done mostly by bikers, all trying
to convince us to go with them. Thanks to Lau, we were fortunate
enough to have Joelson pick us up from the bus station (which is also
the train station). I actually knew Joelson from the 'hood, since he
is a friend of Carla (Nogas), but couldn't recall him when I heard his
name. I instantly recognised him when I saw him. We were just so
incredibly grateful to travel in any kind of comfort. We reached the
hostel and liked what we saw; the facilities were of a very good
standard. But, priorities, priorities! We had to immediately have a
shower, removing the thick layer of dirt that covered us.

We were now officially in Benguela.
