#+title: Notebook of a Return to My Native Land - part 11
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil
#+HTML_HEAD: <link rel="stylesheet" href="../css/tufte.css" type="text/css" />

[[file:index.org][Back to chapter index.]]

Saturday, February 10, 2007

* Benguela

Benguela is one of the oldest Portuguese settlements, a small coastal
town of great strategic importance in days gone by. Nowadays it has
only four or five paved roads, but the many other non-paved ones serve
as a testament to its past grandeur. The city is the capital of the
province with the same name, a position that has forever been disputed
by Lobito, its upstart rival. The province's total population is
around 1.4 million souls, more or less evenly split between these two
cities, with the important caveat that census haven't been conducted
for the best part of fifteen years. Much like the remainder of Angola
outside of Luanda, the province is very sparsely populated.

Benguela was designed in the South African or American style, with
great many parallel roads and avenues, one big square of a place. The
two or three avenues are large, very wide. Due to this design, it is
really easy to learn your way around town. In less than a couple of
days we were fairly proficient, and moved confidently when out and
about. You can move with total freedom at all hours, even at night,
and carry valuables with you without having to worry about it. We
didn't experience a single problem during our stay, even though we
walked the town extensively at all times of the day, and we frequently
carried our camera. This was a greatly appreciated freedom, the
ability to leave the house and roam, not depending on anyone other
than ourselves - something we dearly missed in Luanda. There are a few
places to eat, but not many. Although the prices are still a bit high,
they are much more reasonable than in the capital. Most of our meals
ended up costing between 2000 to 2500 kwanzas for the both of us (25
to 30 USD). A place we recommend is Tan-Tan, a Brazilian restaurant
that specialises in buffet food by the kilo (a popular concept in
Brazil).

The architecture of Benguela is almost exclusively
colonial. Government buildings are solid, large, grand old things,
built in that ostentatious style of one or two hundred years ago. A
large number of these buildings have been well preserved, and a few
key ones were completely renovated. There are important exceptions
such as the immense Post Office building, a majestic structure that
has been robbed by time of a lot of its splendour. The old
anthropology museum, just around the corner from the beach, is an even
worse example of conservation, a skeleton of its old self, only ruins
really. Overall, though, there seems to be a concerted effort from
government to keep their property more or less in order, so one hopes
that the much that remains to be done will one day have its turn. The
biggest problem in Benguela, and I suspect in most of Angola outside
Luanda, are private homes. The vast majority of houses and flats were
erected in colonial times, up till independence in 1974. Whilst Luanda
has seen a massive construction boom in recent years, little has been
built since the seventies outside the capital. In Benguela's case,
almost all properties we've seen date back to the seventies and less
than half of those were in good condition. There are some new houses
being built in the city, but we didn't get a chance to see them since
they're slightly out of town. We did see many refurbished houses, all
quite impressive indeed, with lush greenery popping out behind high
fences, but the worry is that many properties will never get the
attention they deserve. Flats in particular have suffered the most
neglect, but, fortunately for Benguela, there aren't that many large
towers like there are in Luanda and Lobito - the fourteen, twenty
stories high giants. Most of them are less than five stories.

Still on the subject of architecture, A place one must visit in
Benguela is the open air cinema Kalunga. It was recently refurbished,
and sports a lovely esplanada (or beer garden) at the top. Its worth
going there almost at all times, during the day for the shade and nice
cool beer, at night for either the beer or the cinema. You can also
eat some snacks and fast food meals such as fried octopus with chips,
which we highly rate. Unfortunately, the cinema is not making that
much money at the moment, and capacity is far above demand for such a
little town, so its economic viability is in doubt. One hopes dearly
that they manage to make it work. The bar, however, is doing fairly
well, and we got to chat to the manager a few times, Cid, a most
likable character.

Funnily enough, the biggest annoyance we found with Benguela is the
rain, but for very different reasons than the ones we complain about
in England. The rainy season is extremely hot, but it rains almost
every other day at dusk or at night - just when you want to watch a
movie at Kalunga. The rains can go on for a bit, torrential downpours
that leave everything flooded in their wake. The paved roads are not
greatly affected, they dry out as soon as the sun shines and you can
hardly tell it rained. The sandy roads, however, somehow manage to
convert themselves into thick mud, alternating with huge, swimming
pool sized-puddles, and remain in this state for days on end. These
can be extremely difficult to negotiate by foot or even by car. We
were housed in one such road, which made getting in and out of the
house somewhat challenging after the rains. To make matters worse,
these roads aren't pleasant even in the best of times - when rain
isn't around for a few days - since the fine sand they're made of
produces vast amounts of dust when bikes and cars travel across them.

But the negative side of Benguela was more than compensated by its
many positive aspects, including its delicious ice creams and fresh
bread, the niceness of the people, the many means of transportation
available and the beauty of the nearby beaches. Overall, we thoroughly
enjoyed our two-week stay.

** Praia Morena

Praia Morena is the city's beach, nowadays no longer an "in" beach for
the well-off people. Instead, its mainly used by the less wealthy, who
congregate there in large numbers, seven days of the week. For us, the
best thing about it was the short distance from our house: less than
half-an-hour walk. Its not a great beach, but, for a city beach, its
also not that bad, all things considered. The water, whilst clean, is
fuzzy-sandy, making it impossible to see the many fish that swim
around you. The sand has some rubbish lying around here and there, but
perhaps not as much as Ilha, especially if you bear in mind that there
are no concessioned areas with expensive bars in Praia Morena. In
fact, in the vicinity of the beach there are only two bars, probably
more accurately described as cafes, and these only busy themselves a
bit at midday, when a few office workers stroll in for their two-hour
lunch breaks. A fino (draught beer) costs between 50 to 100 kwanzas, a
far cry from the 400 or so kwanzas one would pay in Ilha.

A large road follows the beach for part of its length, but the
partnership soon ends and the road shoots inwards, towards town. The
dividing line between road and beach is a decaying sidewalk shaded by
tall green trees, underneath which lie benches and a long, knee-high
bench-like wall. These are perfect for kipping when the afternoon sun
proves to be too hot, the shade being really cool and breezy, and many
a time we felt obliged to accompany the locals in their afternoon
siestas. On the benches, and on the wall, kitandeiras sit to rest
awhile from their never ending journey, always taking the opportunity
to promote their wares to passers by. They sell all sorts of things,
from exercise books to mangoes, to doughnut-like fried delicacies
stored in great big plastic boxes. Ten kwanzas will buy you a
doughnut. Below, in the parking lot by the sidewalk, large numbers of
kupapatas - the bike taxis - await their clients in convivial
conversation, a typically animated affair. Eventually, slowly, one
drags himself from the group to do an errand, sometimes involving
carrying a passenger with a bag or two, or a large load, or a kid, or
all of these at the same time, all in one small 50 cc bike. Somehow,
both driver and passenger seem to have a deep understanding of the
laws of physics required to make such an improbably loaded vehicle
balance, dynamically, a feat made all the more impressive when one
takes into account the state of the roads. Away they go, slowly moving
towards their destination.

Walking the entire length of the beach, we found it actually extends
for quite a distance. We went all the way to the end, from the
promenade to the point where the ocean meets the local river, over an
hour walk. On the horizon, the never ending green-and-blue sea is
interrupted by fishing boats and some flying fish, all framed on a
background of clear blue skies. There is the occasional cloud. The
coast is populated by a musseque-like fishing village, one or two
stationed boats alternating with one or two houses and vast expanses
of empty space, small groups of village people roaming up and down the
hot sands. An impromptu fish market near a tiny agglomeration of
boats; fishermen and their women selling the catch of the day. As the
river nears, the land becomes greener. All the while, at a distance,
one can see many palm trees and green vegetation. Then, the
intersection between river and sea arrives. The waters become
tumultuous, brown, dangerous. There are little islets of land in the
river. Time to return. The experience is repeated, but this turn in
reverse.

** Baia Azul

Elsa's auntie Teresa put us in touch with a couple of her contacts
that lived in Benguela: Ricardo and Pedro. The guys gave us some basic
tips with regards to the town and its surroundings, where to eat, key
places to visit and such. One of the spots that got mentioned was Baia
Azul. We had heard of it before, probably in conversation with Lau and
Leonor, and talking to the boys made us even keener on seeing the
place. The name translates literally to Blue Bay, and, says who's been
there, its a most fitting description. The boys pointed us on the
right direction with regards to means of transportation but, owning
cars, they didn't know the ins and outs of getting there by
candongueiro. However, they did know somebody who knew someone who had
an inkling on how things worked. Following their tip, we decided to
wake up early and wait on a busy roundabout for a candongueiro heading
towards Baia Azul. Plenty went by, many shouting "Baia". We stopped a
few, but as soon as we asked "Baia Azul?", the cobrador would reply
negatively: "Baia Farta!" and quickly move on. This went on for some
time, so much so that we started to feel that either there weren't
that many candongueiros to Baia Azul or we were waiting on the wrong
place altogether. But, never fear. To our rescue comes a candongueiro
whose cobrador had a big desire to fill the last remaining seats, even
if it required talking to customers for more than ten seconds. Instead
of replying to the usual question with the usual answer, he was kind
enough to point out that no candongueiro actually headed to Baia
Azul. Instead, best thing to do was to go with him towards Baia Farta
and stop at the Baia Azul intersection. There, we could either
hitchhike or walk up - not a huge distance, he says, convincingly. We
jumped in, hoping that this cobrador was not just trying to milk us of
our precious 80 kwanzas. Somehow space appeared in the crowded
minibus - "Are you sure there are two seats available? Where??" - and
off we went. Much to Shahin's displeasure, she was stacked next to a
fisherman who must have just finished taking his fish to the
market. Eventually, after quite some time riding, the cobrador
signalled the driver to stop, in a place that seemed like pretty much
every other place along the way: dry, hot, sandy, a few rocks. Upon
closer inspection, it did vaguely look like an intersection; a sandy
road shot into the distance, but appeared to lead deep into the
mountains. There wasn't much time to think in the rush of the exit,
but once we were out and the candongueiro had left, the precariousness
of the situation became immediately clear. In front of us laid a long,
really long sandy road, heading somewhere far in the distance -
nothing that looked walkable, most certainly not in this heat. Other
than the two of us, there wasn't a single living soul visible in this
huge desert. We waited by the detour for a bit, deciding on the course
of action. What if the guy was wrong, just trying to fool the
foreigners? We had no way of knowing. We could be on a path to
nowhere, walking for hours. We had to be sure. So we waited for
someone, a car, a person whom we could ask. Eventually a car came,
coming from what hopefully was the way to Baia Azul. Not ideal, not a
potential lift - but still, someone. I tried to attract their
attention, to stop them, but they just drove on. As I was about to
return, Shahin shouts. I look back. They had changed their mind. We
chatted. Turns out we were really on the right intersection, and the
distance was actually walkable, hard as it was to believe from
here. So we walked. The road had a turn, a bit further down the
line. Twenty-or-so minutes later we found some houses, and following
that we found the bay.

Baia Azul was practically empty, with the exception of one or two
local kids. The scenery was stunning. The sea in front of us looked
blue like the sky above it and the water was almost still, a whisper
of a wave coming towards the sand. On the left, a huge, towering wall
made of rock sat behind the sandy beach and continued further on,
stretching into the sea. Its sheltering presence gives the bay a
strange cosiness, making it look smaller and safe, but also a bit
eerie with all the silence around you. To the right, the white sandy
beach continues for many kilometres, almost the full
half-circumference of the bay, interrupted only close to the very end
by a rocky formation. The water was so calm it gave the feeling you
could swim for miles, forever forward, all the way to the vast
expanses of the Atlantic ocean.

We stayed at the beach for a good while, enjoying the swim and the
sun. Fortunately we had brought some food with us, as the only
restaurant available was shut. It seemed to only function on
weekends. When the sea is calm, the water is perfectly clear, perfect
for snorkeling. Unfortunately, there aren't that many fish around,
making the experience less rewarding. In terms of rubbish, the beach
is acceptably clean, but, in typical Angolan fashion, nowhere near
spotless.

Around four o'clock we decided to make our way back into town. This
was a very fortuitous decision. When we got into the intersection, all
the candongueiros that went past were so full they weren't even taking
any more passengers. You could see backs and heads coming out of
windows, that sort of full. We waited for a while, more than an hour,
but no luck. Eventually a candongueiro going towards Baia Farta
stopped. We were a bit puzzled, but it had actually crossed our mind
to go all the way to Baia Farta and then return towards Benguela. The
driver must have read our minds because this is exactly what he
proposed (the cobrador was just a little kid, his son). The driver was
an extremely pleasant character, extremely apologetic for anything and
everything that wasn't as he expected. When we got to Baia Farta we
had to wait around for god knows how long, looking for people first
and then loading fish and all sorts of other merchandise - he
continuously apologised for every single delay. Very nice
chap. Unfortunately, the same cannot be said about Baia Farta. The
name looks like a bad pun with farts and the town smells the part: its
a huge fishing town, with never ending rows of makeshift huts where
fish is dried and sold. The smell is overpowering. To make matters
worse, there's rubbish everywhere. At one end of town there is a large
beach - the bay that gives it its name - but, although the natural
scenery is nice, it is totally spoiled by the smell and rubbish. None
of the damage appears to be permanent, mind you, and if the government
decides to invest in some proper housing, Baia Farta may one day
actually look quite nice. This is most certainly not the case at the
moment. Many passengers later, we headed down towards Benguela.

We returned to Baia Azul a second time, but things were very different
and mainly for the worse. We got a lift with Ricardo on a Sunday. Like
him, most people seem to make the bay their destination of choice on
weekends so there were a lot of people around. It wasn't hugely
crowded, there still was lots of space on the sand and all, but it was
very different from our last experience, having the whole bay just to
ourselves. On top of that, the day started with a bit of rain, and
although the weather had settled by the time we got to the beach - the
sun was out and it was really hot - the sea was really rough. There
were half-a-meter high waves. This made swimming a lot more fun, but
it was impossible to snorkel since the water was full of sand. It was
enjoyable, but not quite like our first outing. We had some food in
the restaurant, nothing much due to its makeshift nature.

** Caotinha

If getting to Baia Azul was adventurous, Caotinha can be considered a
voortrek on its own right. Caotinha was the other must-see beach that
everyone kept on mentioning. Unlike Baia Azul, all conversations on
the subject were followed by "Shame its so hard to get there", "You
need a pretty good jeep to climb that hill" or some other statement of
that nature. Unfazed, we decided to take the same approach that
brought success in conquering Baia Azul: get the candongueiro to the
intersection and walk. Just to make sure the distance was walkable, we
asked a few people including Pedro and Cid. Opinions varied. Pedro
seem to believe it was going to be a long stretch whilst Cid was
convinced it was no more than a twenty-minute stroll. Now, we had
asked directions for many, many places before and we found out that,
in general, anything beyond one kilometre is considered too far to
walk by the vast majority of Angolans; poor people would say take the
candongueiro, rich people would say drive - no one, but no one, would
say "hey, that's just down the road, just walk there". To give a
practical example, we had heard that getting from the intersection to
Baia Azul was too far a walk. With all this in mind we decided to give
it a go and repeat the battle plan. The trip started pretty much like
the previous: we got a candongueiro to Baia Farta easily enough and
stopped at the intersection. We even double-checked with some locals
waiting at the intersection; this was indeed the right place. So we
started walking. As we were on our way, the driver of a car going
towards Benguela shouted something like "poor girl, why are you
torturing her??" but it wasn't enough to cast doubts on our
spirits. We kept on walking. The road was long. A candongueiro went
past us but by the time we noticed it, it was too late. We had walked
for a good forty minutes when we reached a little depression, a small
hole, if you like. Nothing much, perhaps fifty metres across. Behind
it, a small mountain, contoured by the sandy road. To its left, the
sea. Was this the "hard terrain" that required a jeep? The sea looked
so close, just behind the mountain, so much so that it made us believe
we were almost there. So we crossed the hole and headed towards the
hill. Less than an hour into the journey and we got to the other side
of the hill. At this stage we realised our task was perhaps somewhat
more difficult than what we had envisaged. There was a large prairie
in front of us, and at a distance to our right, another fairly large
hill. If the beach was near the town, we were perhaps thirty minutes
from it. That was the good hypothesis. The bad hypothesis, however,
was that the beach was behind the hill at the far end of town. This
hill, a small mountain really, could not be circled round - it would
have to be climbed. Hard to even estimate how long it would take to
climb that huge obstacle. As we were contemplating our fate, a couple
of local ladies walked past, a group of middle aged women. They
confirmed our fears. The little village we were heading towards was
called Caota. The beach we wanted, Caotinha, was indeed behind the
mountain and there was no other way to get there other than climbing
it. Around one hour and thirty minutes into the journey we got to the
bottom of the hill, and readied ourselves for the climb. There was a
road of sorts, wide enough for cars, so we thought it was prudent to
follow it even though it was quite circuitous. We followed it for a
bit, until it lead us to the top of the hill. From there the view is
absolutely amazing. You can see the little village below, and further,
you could clearly see Baia Azul. The rocks we had previously spotted
don't allow walking from Baia Azul to Caota, but from up there one
could see the interconnection between the two places. The entire bay
is huge. We could also see just below us the Caota shipyards, probably
the only reason for the existence of this little town in the middle of
nowhere. A couple of wrecks there. As we continued walking, the other
side of the hill appeared. A set of stairs led down to a little cove,
and it seemed really inviting, except that there were many, many
steps, hundreds if not thousands, and by then we were weary and tired
and the sun was at its hottest. Instead, we decided to find an easier
beach, hoping one did exist. Less than a mile down the road, a few
houses appeared: a little restaurant, which much like Baia Azul's
seemed to only function on weekends, and a smattering of small and
middle sized beach houses. Just behind them, not even five minutes
walk, laid the beach. It took us just short of two hours to get to the
beach.

All the efforts were repaid in full, though. The small beach, another
cove really, was totally empty. It is protected by a set of rocks,
that are also used by fish as breeding grounds. Little bits of reef,
or reef like things, grow on the rocks. If one was already amazed by
the scenery, snorkeling was beyond words. I've never seen so many
fish, of so many different kinds and colours, in one single
place. Unfortunately, my knowledge of fish is rather limited so I
can't even name one. Just when a marine biologist is needed,
Shelbourne is not around. Due to the rocks, and the general roughness
of the sea, it was not easy to get in and out of the reef so Shahin
didn't really get to experience much of it. I, however, spent pretty
much every single moment in the water, just coming out to warm up. It
was an amazing experience.

Things were much easier on our way back. We climbed the hill, and
investigated the shipyards a bit. The local kids seem to have loved
us, and Shahin's camera. Eventually we decided to crisscross town, and
much to our surprise a candongueiro appeared. This was extremely
fortunate since there aren't that many doing the Caota route - three
or so, with totally unpredictable timings. And there was even a couple
of places left too, on an otherwise packed candongueiro. Our lucky day
indeed.

** Benguela's Market - or Caotinha part two

Our second outing to Caotinha was equally eventful, but for very
different reasons. To make our lives easier, I had gathered some
intelligence on the candongueiro routes during our previous trip. A
fellow passenger had told me that the starting point of the journey
was the market, just by the stand where goat meat was sold. Buses left
from six o'clock in the morning onwards, but the only exact time was
for the initial departure - all other times were dependent on journey
time. After much debating on whether it was feasible to return to
Caotinha or not - the two hour hike was etched on our minds - we
decided to give it a go, but now taking the correct candongueiro
rather than walking. The first step was to find the market and the
goat meat stand. It appeared an easy task, as we knew the general
direction in which to walk. However, one thing we didn't account for
was that the roads were extremely muddy on that day, and that the
poorer areas have much worse roads than the ones near the town
centre. This was a very costly mistake that made our lives much harder
by many orders of magnitude. Taking a single step required deep
concentration, and there were many close call situations where one of
us almost fell flat on our faces (or backs). Falling would have been
disastrous because we were all walking in single file, with people in
front of us and behind us, and a slip would have meant taking quite a
few people down too. Fortunately it didn't happen, but it came pretty
close a few times. The locals were much more practical than us, most
of them walking barefoot to get better grip. We, however, feared the
general discomfort of stepping on mud - not to mention the fear of
cutting our feet - so we kept on walking with our sandals on. To make
matters worse, one of my extraordinarily expensive hiking sandals
decided to break there and then. Although Karrimor guarantees them for
at least a year, mine didn't even last two months. That's when the
ridiculousness of this guarantee business becomes apparent. I mean, if
your shoes break in the middle of nowhere in a six-month trip, are you
expected to carry them for the remainder of the time and walk barefoot
all the while? Hardly. For more than half-an-hour we trudged towards
the market, feeling, calculating each single step. Eventually we
reached the market. However, our troubles were far from over. Instead
of a nice, small market like say the Benfica market in Luanda,
Benguela's market is HUGE. In all aspects. Its massive in terms of
area, in terms of the number of people around, in terms of the types
of merchandise for sale. And this market is made by the locals, for
the locals - we didn't even spot any mulattoes, let alone white or
Asian people. We just didn't know where to begin looking for the goat
meat stand. Its one of those things, probably trivial once you know
what you're looking for, but absolutely impossible for someone who has
never been to a proper African market. We were dazed for a few minutes
in the midst of all the confusion, candongueiros going up and down,
people shouting everywhere, different kinds of animals everywhere too.

On the plus side, we were at the right place to fix broken shoes, or
so we thought, so as soon as our heads cleared and adjusted to the
surroundings, we went in search of a shoemaker. We were a bit
intimidated by the fact that we stood out like sore thumbs, but there
wasn't much we could do about it, so we just got on with the task at
hand. Due to the structure of the market, with its very narrow roads
overflowing with products, compounded by the mud and the crowds, it
was actually very difficult to negotiate our way round. On top of
that, we had to ask every five seconds for some more clues, since the
directions we got from everyone were pretty sketchy. I'm not entirely
sure how we managed to find the shoemaker, but somehow we did it. It
took a good deal of asking and searching, of trying to decipher clues,
but in the end the chap was there, fixing another customer's shoe. The
shoemaker was old, probably in his fifties or sixties, and he worked
slowly and patiently but with great dexterity. His tools were all
hand-crafted and seemed to fit their purpose very well. He finished
the previous customer's job and then turned his attention to
me. Without much explanation from my part, he immediately diagnosed
the problem and started working in fixing it. With no mercy or regards
to brand names, he hole-punched, sowed, and hole-punched some
more. The fallen strap was back in its rightful place in no time at
all and the sandal felt as solid as before, if not more. The job was
done in a fairly seamless manner. I felt somewhat guilty in paying the
craftsman the fifty kwanzas he demanded, so I added an extra twenty -
not quite enough to make me feel good about it, but at least the
gesture was appreciated by the shoemaker.

We then went back to hunting the goats. After much misleading
information - we walked up and down, up and down the market - we ended
up settling on a stand that had a few goats, although these ones were
alive and walking about. It wasn't quite what we expected, but then,
what had we expected? There were candongueiros stopped everywhere,
going to several destinations. Swarms of people everywhere. Many
candongueiros were heading to Lobito, others to Catumbela and other
nearby towns. However, we couldn't find a single one going to Caota,
nor could we find a person able to confirm the usual departure point
of these candongueiros, tried as we might. We asked lots of people,
but no one knew anything useful. After standing for a while, it became
clear that we were not going to find the right goat stand. So our only
other option was to take a candongueiro to Baia Farta as we had done
previously and walk the road up yet again. This was not a pleasant
option, but the confusion of the market was fast becoming unbearable
and we had to do something. We had to go for it.

The candongueiro dropped us at the intersection and we started
walking, but this time we decided to try our luck at hitchhiking. To
our great surprise, not even ten minutes into the walk and a huge
truck stopped. However, we were somewhat confused as there were no
empty seats in the cabin, and the cargo compartment at the back was
just a huge big box, not really the sort of place one would put
people - not unless you're smuggling them across the channel. The
driver insistingly pointed to the back, so we went round. When we got
there, dozens of eyes stared at us. It wasn't really a closed cargo
compartment, it was more like a cattle transport truck - but instead
of cattle it transported people. The vehicle was a kind of
candongueiro and it was full to the max, or so we thought. That is,
until the cobrador started shuffling people around a bit to make
"space" for us. I would hardly call "space" to what he came up with,
but we had to make do. Shahin kept on mumbling something like "I ain't
getting in there man, I rather walk!" but it was too late since I was
already in the truck. She somehow managed to jump in. The thirty or so
minutes that followed were, up to this point in time, our worse ever
trip in any means of transportation we have ever travelled in - and
this includes the twelve our bus trip to Benguela. Truly. We were
standing up, crammed, surrounded by dozens of people, unable to move
even one centimetre in any direction, holding on hard to a metal bar,
hoping that it wouldn't somehow break. Shahin held so hard she had
bruises afterwards. The truck was moving at incredible speeds, or so
it seemed for us at the back. To our great relief, around thirty
minutes later we arrived at the entrance of the Caota village, where
many of the passengers left. The remainder of the trip was done in
great comfort and Shahin even managed to find a seat on top of a pile
of corn bags. The people on the truck were awfully nice, and made sure
we stopped at the optimal place to start our climb to Caotinha. It was
then that Cid's comments made sense; of course, its only a
twenty-minute stroll from the bottom of Caota to Caotinha. The problem
is getting to Caota. The climb wasn't half as difficult as last time,
and we even decided to take some shortcuts.

Whilst Caotinha was still very nice, it was not as nice as the first
time. The weather was hot and cloudy and the sea was much rougher,
with some real waves hitting the reef. This made it really hard to get
in and out of the reef - even downright dangerous, since a wave could
force you against the rocks. I still managed to snorkel for quite a
while, but nowhere near as much as last time. On our way back, we
waited for over two hours in the Caota village for a
candongueiro. There really isn't much to do in the village, so we just
loitered around the only "bar" we could find, getting stared at by all
the locals. Eventually we gave up and started walking. It was getting
late, dusk was setting in. Suddenly we spotted a candongueiro going
towards the village and we chased after it. It was a good chase,
across huts, up and down roads, but eventually we got it. Once we were
in it, we found out we were waiting for the candongueiro at the wrong
place. This was actually the last one for the day. We got lucky yet
again.

** Cubal

Another place that had been mentioned in our conversations with Pedro,
Ricardo and Teresa was Cubal. It was described as a small city a good
hundred kilometres in land in the Benguela province, with fantastic
scenery on the way there. Pedro suggested getting there by train,
using the CFB. Angola is currently restoring much of its
infrastructure, and trains are a vital part of this effort. There are
three main train lines: the CFL (Caminhos de Ferro de Luanda), the CFB
(Caminhos de Ferro de Benguela) and the CFM (Caminhos de Ferro de
Mocamedes, in Namibe). All three are being worked on, but of these,
the CFB are the most important link since they will connect Zambia to
the port of Lobito. In the past, this was a hugely important economic
link, used to export Zambia's copper. Unfortunately, the work is still
underway so trains in Benguela are still pretty sketchy. The trip to
Cubal takes over 6 hours - the train is pretty slow - and trains only
run on Mondays, Wednesdays and Fridays. Since there isn't much to do
in Cubal, going by train was not an option.

As we were speaking to our landlady Dona Judite about this, she
mentioned that her husband, Senhor Chico, was going to Cubal in a few
days time. Senhor Chico was extremely kind: not only did he agree to
take us there, but he also found us some accommodation at no extra
cost. He was currently doing a project for the local government in
Cubal, a small hotel, and some of the rooms were already finished - we
could sleep in one of them. This was a perfect arrangement, so we set
on our way. The trip there was over five hours long. The road is
mostly non-existent. In fact, as he was apologising for the haphazard
driving, Senhor Chico told us a joke that describes driving in Angola
perfectly: "In England you drive on the left; in Portugal you drive on
the right; in Angola, well, you drive wherever you can." If you have
never driven in Angola you won't understand how true and close to the
bone this joke is, but for us it summarised our experiences. Senhor
Chico could spend ten minutes driving on the left, followed by
half-an-hour on the right, all the while jerking and twisting past
holes. It must be a funny experience seeing somebody drive from up
above; its almost like they're following an invisible road, turning
where there doesn't seem to be any apparent turns, stopping in the
middle of nowhere, leaving the road on detours that are not signalled
at all.

Whilst the drive was not particularly pleasant on the stomach
department, the eyes had plenty to feast at. The road to Cubal is full
of greenery, increasingly so as you head towards the interior. Its
similar to what we had experienced in Kanjala, just lush greenery, but
here there are these high mountains in the background, and these huge
rocks laying in the green prairies. Like Teresa had said, it is as if
these rocks could talk, its an eerie experience. To make it even more
eerie, Senhor Chico kept on mentioning how impossible things were
during the war.

- "You couldn't drive around here in those days, no sirree. Ambushes
  all the time. You can still see the remainders of the wrecks, like
  that one there" - he says, pointing out to a bit of rust at the edge
  of the road. Greenery everywhere made the valleys look so
  peaceful. But they still looked like perfect places to ambush.

Half-way through our trip we stopped in a little town. Senhor Chico
had some business to conduct there. This was a very little place, ten
houses or so, a nice little village in the middle of nowhere. We were
soon back on our way. In just over five hours we reached Cubal. The
trip took this long because the pick-up truck was extremely loaded and
we had to proceed slowly. Just as we were about to get into town and
conclude yet another epic journey, a surprise awaited us. The main
bridge that leads you into the town is broken, and has been broken for
over a year. Senhor Chico pointed this out, in is usually dramatic
tone:

- "See that over there? That's the town. We're perhaps five minutes
  from it, were we to go that way. Unfortunately, we have to go the
  long way round."

The long way round involved a lot of off road driving and dodging some
really big holes, but the scariest bit of the drive was by far
crossing the temporary bridge. This was a metal structure with a
couple of metal panes covering the fast river moving below
you. Standing before the bridge, it certainly didn't seem fit for
people or animals - let alone five tonne trucks. It was very narrow,
not much wider than a truck, and had absolutely no side protections,
so if your steering wasn't absolutely straight you'd get to swim with
the fish. That's, assuming the bridge would take your weight, of
course, which seemed like very unlikely from where we stood. But, to
our great surprise, a huge SGO bus crossed the bridge before us and
disappeared in the distance. Then, proceeding slowly, we too crossed
it, hearing the loud creaking noises metal makes. A few seconds later
we were on the other side. Fifteen minutes later we entered the town.

In the sixties, Cubal was a booming town due to its sisal
industry. Sisal is a straw-like material used to make baskets, mats
and the like and was extremely popular in the fifties and
sixties. Industries here boomed, much like they did in the rest of
Angola, mainly due to the extremely cheap labour - free in many
instances due to the "contract" system. This allowed Portuguese
settlers to accumulate huge profits in very short time, and these
profits were channelled to create lovely little colonial towns like
this one. Once the war started the industries died, and along with
them they took the towns they previously supported. All that is left
of Cubal are its decaying colonial houses, the ruins of the sisal
factories, an eerie, ghost-like town. Some of it is now being
renovated, thanks to government's money, but one can see that Cubal
will never be what it was - perhaps because like most of Angola in the
sixties, it never "was", really; a fabrication; an invention in
someone's mind. A castle in clouds. Nothing that could ever be
sustainable.

We spent a whole day in Cubal, but there isn't much to do. After
walking the entire town, we found the only existing cafe with its
decaying pool table. There I played some pool with the locals, a sport
that seems to involve every single person in the bar. Some of the
chaps at the bar were part of an NGO demining team called HALO, and
were working in nearby areas. In fact, Cubal was the only place in the
whole of the Angola we've seen that had a sign "Do not walk: mines
here". The HALO people and the locals were very nice and friendly,
much like all other Benguelenses. At night we had some food in a
"restaurant", but the "restaurant" is really someone's house, someone
you can trust and who allows certain people to eat there, for a
fee. There are no restaurants as we know it. We were also quite lucky
to stay with Senhor Chico since we didn't spot a single hostel, so
accommodation would most likely be a problem. All and all, it was well
worth visiting Cubal, but its not the sort of place you can spend more
than one day in.

The trip back was done on our trustworthy Interprovincial SGO buses,
the same that took us from Luanda to Benguela. It was much more
pleasant this time round though. Although the roads were equally as
bad, it somehow felt much safer to travel on the bus this time round,
so much so we even slept for a good part of the journey. It also
helped that the trip only took three hours and a bit.

** Lobito

One weekend we were invited for lunch at Teresa's, Elsa's auntie - my
auntie too, really, in the African paradigm of extended
families. Teresa is one of my favourite characters, a most likable
person, full of knowledge and experience but never showing off, always
making everyone around her feel clever, always making sure everyone is
alright. She is at present working for a Portuguese private
university, Lusiada, located in downtown Lobito. I know of very few
people who are so thoroughly Angolan and so passionate about Angola
like Teresa, so when she heard the call to came and help out, she left
her very successful law career in Lisbon and headed back home. We were
invited for lunch, but like all African lunches it was expected to
start late and last well into the evening. We waited around for our
lift, but he was running late, so we decided to take our chances with
the local transport system which we grew to know and
love. Candongueiros leave from Benguela to Lobito at all times, but
unfortunately they are almost always full by the time they cross
town. Fortunately for us, one of the chaps waiting at the bus stop was
extremely friendly, and not only did he explain how to get to Lobito
but he also gave us his seat when a candongueiro appeared with a seat
or two available. This was an unimaginable act of contrition which we
really appreciated since we were all waiting for over an hour.

There's only one word to describe the road from Benguela to Lobito:
dangerous. For various reasons. First, the road is narrow, in most
places with only a lane in each direction, and in some parts covered
in thick dust. A Chinese company is busy doing an extension to convert
it into a dual-carriage way, but the work will probably last another
couple of years or so. Second, there are huge amounts of kupapatas
driving up and down the road, most riding their bikes pretty slowly
and orderly but some do it at crazy speeds or perform crazy
stunts. This also means one spends most of the time overtaking
bikes. Thirdly, a lot of the car drivers on that road are just plain
crazy. They drive at unimaginable speeds, particularly at
night. Luckily, we never saw or were involved in any accidents on the
many times we were on that road - but we were close to being in one,
as I'll explain later. The panoramic views are excellent though, on
those short seconds when you manage to get your eyes off the
road. There are trees all around, and lots of vegetation. This area
once housed Angola's sugar industry and one can clearly see why, green
jumping at you from all places. At the end of this interconnecting
road is a bridge, designed by the French engineer Eiffel. It does look
the part, sharing many similarities with the Paris tower and Porto's
bridge, such as the massive usage of metal. The bridge is in dire need
of some renovating though, looking very old and decrepit. One cannot
but hope that some money is channelled for this soon, before the
damage is irreversible, but this may not happen since architecture and
landmarks are hardly the government's first priority. We drove on for
a bit longer, but the cangongueiro route ends at the entrance to the
city, well before our destination. There we had to catch another
candongueiro, this time to Bairro Vinte e Oito. This candongueiro
stops one block away from the University. The University itself is
located just behind the Port of Lobito, Angola's most important port.

Teresa lives in the residence halls, in Angola exclusively destined
for teachers. This is because a large number of the teaching staff are
either foreigners - mainly Portuguese - or Angolan returnees, who have
no housing of their own. Housing is thus one of the perks used to
attract employees, in particular because decent housing is so
expensive to obtain. The apartments are very nice, charming little
places, sporting tall, wide rooms - but unfortunately not many of
them. They are really made for one or two people at most, and most
teachers are youngsters out of university precisely in this
situation. Teresa had invited some of her colleagues for dinner: Dr
Napoleao and Dr Edgar, in addition to Teresa's Mom. Both doctors were
very likable chaps, and Shahin took a particular liking to Dr Edgar
since he spoke fluent English. He had lived for a long time in
England. The food was excellent and the conversation too, and we
debated well into the evening all of our country's problems and
strengths, and our role in its future. At one point I was bemoaning
the sad state of Information Technology in Africa in general, and
Angola in particular; how we were to yet again lose another race, even
before it had started. Dr Edgar's response was extremely insightful,
although he was kind enough to state it in a very nice way. Truth is,
people like me just love to sit and complain, without actually
stepping up to do something about it. This is common to most of the
diaspora. I am not ready to come and teach IT in Angola even though my
contribution is dearly needed. So many of us sit in our lovely little
porches in our lovely little houses in Europe, in America, with our
nice jobs and our nice lifestyle, and moan from afar. You see this in
the web forums, in the parties, in the gatherings. We complain on how
things are being done ever so incorrectly, how so much money is being
wasted, how so many important factors are not being taken into
account. In reality, many of the people that took the plunge and
decided to get their hands dirty are doing a sterling job given the
constraints; and there are many, many constraints, many of which you
only begin to understand when you are there, in situ. What they really
need is for more qualified Angolans to come and help out
reconstructing their country. Whilst many are coming, the numbers are
nowhere near the requirements.

Once the dinner was finished, after we satiated ourselves with the
lovely pudding made by Teresa, it was time to get back to Benguela. We
got a lift with Dr Napoleao. This time it was really dark, that sort
of dark you only see in Africa. As we were driving back, perhaps forty
minutes into it, one of the kupapatas riding ahead of us decided to
park up on the side. But, as any good Angolan would, he didn't park up
to his right, the closest side, nor did he look back to see if there
was anyone behind him. Instead, he turned wide to his left, slowly,
unexpectedly, and moved towards the other side of the road. This, in
the extreme dark, with almost no lights at all on the
bike. Incredible. Fortunately for us, Dr Napoleao is a pretty good
driver, and managed to somehow avoid the kupapata, but it is
remarkable the faith that some of these people put on other drivers.

We returned to Lobito some days later, this time to actually
investigate the town. We were lucky to get dropped off by Dr Napoleao
and taken back by him too. We spent most of our time at Terminus, a
lovely grand hotel in Restinga. Restinga is Lobito's Ilha, identical
in shape to Luanda's but much wider. Much to the grin of all
lobitangas, I, a kaluanda, had to admit Restinga is much nicer than
Ilha. It has lovely colonial houses, wide roads and parks. It's also
much cleaner. Terminus has a lovely beach behind it, similar to the
concessioned beaches in Ilha. One can eat at the hotel for very modest
prices, and we had two omelettes, very nice indeed, setting us back
less than 2000 kwanzas for the both of us.

Our third visit to Lobito was rather... interesting. We were invited
to the launch party of the Lobito's offices of a new law practice. The
partners are Teresa, Dr Napoleao and Dr Jaime, and Teresa insisted on
having us there. I did warn that we didn't have any special clothes
other than jeans and t-shirts but she said it was going to be a small
affair. We got picked up and dropped off by Ricardo. The party was at
the posh Navegante hotel. We should have remembered how Angolan's love
to underestimate things. I mean, really. Even the television and radio
were there. The head of Lobito's port was there. And the three of us,
Ricardo, Shahin and me, were the only ones wearing casual
clothes. Shahin was dolled up enough, but being a girl kept on
complaining all night long. In total, there must have been over one
hundred elegantly dressed, fashionable people, a sort of Hello
magazine party for Lobito. However, as soon as we started chatting to
people we quickly got into the swing of things and it ended up being a
really enlightening experience. We got to meet lots of Portuguese and
Angolan returnees, some captains of industry and important people, to
really get a feel for what is happening in the country. It ended up
being a fantastic experience. The party lasted well into the night,
dancing involved and all, but we made a move around midnight, since we
still had the long drive back.

Our last visit to Lobito was via candongueiro. This time round, we
decided to go to the end of Restinga, to one of the non-concessioned
beaches. It was very nice, and fairly clean. We swam first on the
inner side of the bay, the side facing the town. Shahin loved the
water here, incredibly quiet, and I liked the snorkeling too. There
were lots of fish in the water. It wasn't anywhere near the variety of
Caotinha, but the fish here move around in large schools, very
impressive numbers. The scenery is stunning too, with large mountains
and the town. We then went to swim on the Contracosta, the ocean
facing side of Restinga. Much like in Mussulo's, the sea here is
rough, wavy, harder to tame. The snorkeling is great too, but one
cannot avoid thinking that a shark is looming around.

All and all, we liked Lobito quite a lot, but not as much as
Benguela. This is because the city sprawls a lot more, making it
really hard to walk round. Just Restinga itself is huge, requiring a
candongueiro to go from one end to the other. Also, whilst there are
many nice neighbourhoods in Lobito, there also appear to be many more
musseques, particularly at the entrance of town, making it look like a
shabbier place. This is not true at all, and one can confirm that by
going to Bairro Vinte e Oito and Restinga, and probably many other
places we never managed to get to, but still. So as far as we were
concerned, Benguela won the battle, but only marginally.
