#+title: Notebook of a Return to My Native Land - part 1
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil

[[file:index.org][Back to chapter index.]]

Wednesday, November 08, 2006

/The grand tour is just the inspired man's way of heading home./ -- Paul Theroux

* Human Errors

So there you go. 8th of November is almost gone. That leaves us with
another 21 days before we depart from sunny old Albion. And yes, we
still haven't got a visa for Angola, nor accommodation for Luanda, nor
any idea of how to get from Luanda to any of the provinces (the
Angolan counties are known as "provinces"). How do two fairly
experienced travellers get trapped into this situation? After all, me
and Shahin, we've seen one or two countries in our time. How hard can
it be to plan a six-month trip to southern Africa, right?

If you know me - and, chances are you do since you are reading this
blog - then you also know that one of my most distinguishing traits is
this extreme, unflinching (some would even say pathological)
optimism. I'm the sort of guy that, having one day to plan an
expedition to the Artic, would probably say "hey, how hard can it be,
right"? A perfectly fine attitude to have when facing most day-to-day
situations; alas, organizing a big trip is not your normal day at the
office. But I digress. Lets return to the beginning.

I've been meaning to visit my country of birth since, well, pretty
much since I've left it, many moons ago as a young kid. Somehow I've
managed to convince sensible Shahin that this would be a good
idea. She, in turn, managed to convince me that it would be wiser to
also see a few other countries in the region rather than just plonk
ourselves in Angola for a while. In the end, the choices came down to:

a) paying a deposit for an expensive, matchbox-sized, one-bedroom flat
   in zone 15 of the quaint but rather inefficient English transport
   system; or

b) fool ourselves into believing that the property ladder is actually
   not at all important, and instead spend six months seeing a bit of
   my continent.

Not much of a choice, really.

We started by investigating the visa requirements for all the
countries we would like to visit. The list was long, but we somehow
managed to go through it. A bit too quickly, perhaps. We concluded
that, with a few exceptions, the visas were actually not that
bad. South-Africa, Namibia, Mozambique, Zambia, Botswana and even
Zimbabwe had fairly sensible visa requirements. Angola's was a bit
more complicated but workable. So we went and booked the tickets. Yes,
you read that right, we booked the tickets. Yes, before we got the
Angolan visa. To the inexperienced this sounds like a trivial mistake,
easily solved with a trip to the embassy; worst case scenario, a
day-off wasted.

First big mistake.

In addition, we planned to go to Angola around March time. Now, since
we aimed to leave the country around the end of November, that meant
that we would only get to Angola more than three months after leaving
London.

Second big mistake.

Lastly, we assumed we would be able to stay with family or friends in
Luanda, or, worst case scenario, to find a cheap hotel. After all,
anything will do for a couple of tired backpackers.

Third, very, very big mistake.

* Anatomy of a Visa

As anyone who has done real travelling knows, visas are actually a
tricky beast. Not the less seasoned traveller, however. He takes them
for granted even without realising. For example, he may assume that
all countries have a tourist visa. He may assume you can get a visa in
any embassy of the country you wish to travel to. Or he may assume
that, once you have a visa, that's it, you're sorted.

Unfortunately for us, Angola did not have the concept of a Tourist
Visa until very recently. In fact, as recently as two weeks ago. The
next best thing is an Ordinary Visa. But don't be fooled by the name:
there's nothing ordinary about it. To get one of these, one needs to
have an invitation letter. The gist of the invitation letter is that
an Angolan citizen, or a foreign citizen residing in Angola,
guarantees the stay of the person requesting the visa. The letter must
be faxed to the embassy from an Angolan telephone number. If the
person sending the invitation letter is Angolan, you must also include
a photocopy of the person's passport, authenticated by notary. Getting
one of these photocopies would set you back at least 10 EUR and one or
more days of queuing. In addition, the person requesting the visa must
also bring a copy of the letter with them. And, to make things more
interesting, the consulate only receives applications on Mondays and
Tuesdays, from 09:00 to 13:00. That is, of course, excluding all
English and Angolan public holidays. And, oh, you must also bring the
plane tickets with you, so abandon any ideas of getting a visa before
you buy the tickets.

Luckily we know a lot of people in Angola. We'll expand on that in a
moment. For the time being it suffices to say that our friends Lau and
Leonor live there. So, we thought, lets ask them for the invitation
letter. That's when Lau mentioned that we could not possibly be trying
to get a visa for March next year since visas had a 60-day
expiration. "No, it can't be", we protested. "The UK Angolan embassy
website explains the visa process fairly well and there was no mention
of an expiration date". We held steady, convinced against hope that
this was, perhaps, a quirky behaviour of the Angolan embassy in
Portugal. So we rang the embassy in the UK, and after many, many
attempts, we got through to the consulate. The consulate dutifully
informed us that, yes, Lau was right. "But can we at least get a visa
from South-Africa or Namibia?" Best to check with the embassies in
those countries, but, no, not very likely. So we rang these
embassies. It turns out you can only obtain a visa from the embassy of
your country of residence. In the words of one embassy worker:

#+begin_quote
"Para voce ainda se arranjava qualquer coisa, com um pouco de sorte,
talvez um visto de emergencia... Agora para a inglesa, aih nao dah
mesmo, a situacao estah bloqueada."
#+end_quote

Which roughly translates to "perhaps for me they could, maybe, sort
something out. But definitely not for the English woman". Shahin was
out of luck. "Situacao bloqueada", or "the situation is blocked" has
become one of the most heard phrases, and a bit of an in-joke for us
these days. Leonor graciously offered us some contacts here in London,
but to no avail.

We were stuck with tickets we could not possibly use. And refund is
not a word travel agents know of.

* The Angolan Dictionary

After much rumbling and thinking, Shahin found a solution. Whilst the
travel agents were unwilling to refund the tickets, they would allow
us to change the dates of the internal flights - for a modest fee, of
course. In other words, we could go to Angola earlier on provided
there were seats available.

To avoid getting into further problems, we decided to sort out the
accommodation before changing the tickets. "Just in case; hey, you
never know".

In fact, as we now know, accommodation in Luanda is an intractable
problem. Leonor and Lau looked high and low for something for us, but
nothing was to be found. We started panicking slightly: if two locals
are saying hotels are really hard to find, maybe there's a bit of a
problem? It turns out hotels in Luanda are scarce, and thus,
horrendously expensive. Expensive beyond comprehension. And this is
coming from a Londoner. In Luanda, you may count yourself lucky if
you're paying 250 USD a day in a motel; some hotels charge 1000 USD a
day. That is, if you can find a vacant room at all.

Ah, but I was prepared! Whilst I tried to avoiding bugging family and
friends as much as possible, I reserved them for emergencies. And this
sure was one. If there's anyone who knows people, that person is
Mom. So I rung Mom and Mom rung and rallied all the Angolans. In the
mean time, I rung my faithful cousin Elsa, ever helpful.

After patiently listening to my explanations, Elsa then, also
patiently, explained the real meaning of words in Angolan
Portuguese. This was a most enlightening experience. It is a common
mistake people make to interpret literally things Angolans say. For
instance, if someone says "if you come to Angola you can stay in my
house", they are not actually saying that, were you to come to Angola,
you can stay at their house. Instead, think of it a bit more like an
Englishman says "How are you" when he greets you. He is not actually
wanting to know how you are; its just a statement. It could have
easily been "What a dreadful weather!". This applies to almost any
Angolan statement of intention. For instance, if someone says "we'll
see what we can do", this does not mean you don't need to worry about
it and wait for them to come back to you. Instead, you can safely
assume that nothing will happen unless you ring them 10 or 20 times.

Unfortunately, time was running out. And accommodation was not
forthcoming. So we changed the tickets without having a place to stay.

* Expect the Unexpected

The travel agents found us a ticket on the 11th of December. However,
when we reported this to Lau, we then discovered that they were going
to leave the country on the 8th of December. And we also discovered
that its not a good idea to have an invitation letter sent by someone
who is unable to pick you up at the airport. This is because the DEFA
(the Angolan emigration service) may actually want to ring the person
who sent you the letter. And they would not be entirely pleased when
they found out that the person who sent you the invitation letter is
actually not in the country. After all this trouble, being locked up
in a room answering questions didn't sound very seductive.

So the only certainty we had until then, the invitation letter, was
now lost. Now we were back to square one.

As I was explaining this to Lau, he said "yeah, I know. In this
country, one cannot take anything for granted". And he told me about
that time when, after much effort, he had secured a plane ticket to
visit to one of the southern provinces in Angola. He had actually
boarded the plane, and it appeared ready to take off. Then, on the
last moment, an announcement was made: "O motor nao pega, o voo estah
cancelado" ("The pilot can't get the engine to start, so the flight is
cancelled"). I suppose he was lucky to find that out before the plane
took off.

So we learnt another lesson: in Angola, always expect the unexpected.

| [[file:index.org][Back to chapter index.]] | [[file:part_2.org][Forward to next chapter]] |
