#+title: Kizua Mwangola: Part 6: Benguela
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil

[[file:index.org][Back to chapter index.]]

Monday, December 07, 2009

We've finally arrived at the destination: BENGUELA!!! We still need to
sort out Shahin's documents, but since she still has two Ordinary Visa
renewals, which take us to the end of the African Cup we're not too
worried right now.

Benguela has improved a lot since we were here last. The roads are now
paved, and there is a revolution with regards to side-walks. Its
beginning to shape up like the Benguela of old.

We've also managed to sort our accommodation for the next 2 months, a
key worry of ours. The price is steep, but its much lower than
anything on the market; it's also the place in which we stayed three
years ago. Now, all we need to do is find jobs!

Shahin has progressed more than me on this department as she has made
friends with the American expat that runs an English
school. Unfortunately, as the semester is winding down here, the work
is also slowing down. Things look good for the next academic year
though.

I've also managed to open up a bank account and get myself a bank
(ATM) card.

| [[file:part_5.org][Back to previous chapter]] | [[file:index.org][Back to chapter index.]] | [[file:part_7.org][Forward to next chapter]] |
