#+title: Kizua Mwangola: Part 7: Kick'em while they're down
#+author: Marco Craveiro
#+options: num:nil author:nil toc:nil
#+bind: org-html-validation-link nil
#+HTML_HEAD: <link rel="stylesheet" href="../css/tufte.css" type="text/css" />

[[file:index.org][Back to chapter index.]]

Saturday, January 09, 2010

So yet again our hopes were dashed. These past couple of months since
we arrived here, up to last Friday, have been nothing short of
amazing. The whole country was involved in a giant wave of
positiveness, as if nothing could stop us now; as if the long war and
the troubles were something that could and had been overcome; as if,
like England, Germany or Vietnam, we too had the right recover from
the war and build something, to move on. It was great to be part of
this wave. But, just like in the past, it felt really bad to see it
crash, hard against the rocks. Angola just seems to be one of those
luckless countries.

Truth to be told, the bullets didn't steal any of the roads, bridges,
hospitals, school's or even stadiums: those are still standing. The
losses feel far greater though. The bullets stole Togolese and Angolan
lives, and they stole the Angolan belief in a hard-earned decent
future, a future paid in blood and with interest. They made everyone
realise that, no matter how hard things were to earn, they can be
harder still, forever out of one's reach. Just like the bombings in
London or in Madrid, a very small number of people managed to inflict
extremely severe damage to millions. Unfortunately, unlike Madrid and
London, no-one will remember this incident as a terrorist attack;
instead, the insanity was to ever conceive the idea of having "a
high-profile tournament held on a country were civil war is rife", as
a commentator put it on the BBC's forums.

As I walk through the long, wide avenues of Benguela, admiring a few
of our new sidewalks and the manicured gardens behind fences, as I see
a bunch of young boys joyfully going to basketball practice, I cannot
help but think that the world's view of Angola will never change. And
I cannot help but to be cynical. I wonder how many of those who are
now incensed about "countries rife with civil war" even watched the
last CAN or the CAN before that. If deaths occurred then, media
coverage would have been next to non-existent, nothing but numbers
flashing at the bottom of the screen. Now that their teams' backbones
are in Africa, suddenly its at the top of the global news agenda.

Yesterday, the mother of a good friend of mine said: "You're wearing
that t-shirt? They've started killing people already". I looked at my
CAN top with the palanquinha and sighed. She spoke in a nonchalant,
matter-of-factly sort of way --- the weary voice of someone who's been
through it before. Too many times before. "Too good to be true, hey?",
my nod said without needing words.

Lord have mercy. Lets pray we can still make _something_ out of it.

| [[file:part_6.org][Back to previous chapter]] | [[file:index.org][Back to chapter index.]] | [[file:part_8.org][Forward to next chapter]] |
